### ISSUE TITLE
Admin Login Placeholder Layout

### ISSUE THREAD

**Issue by buttflattery** [luyadev/luya-module-admin#1]
- OS Information: Windows 10 Pro
- System Type:   64-bit OS x64-based Processor
- Browser Info: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Browser Info : Firefox 57.0 (64-bit)

The `admin login` interface where we provide the credentials if you directly copy the `email` inside the email input field the placeholder shows up like the following 

![image](https://user-images.githubusercontent.com/1536454/33957604-ea9dc598-e063-11e7-9357-2372cd1b7ebf.png)

**Comment by nadar** [comment]
@dev7ch @TheMaaarc Maybe we can watch this behavior with js?

**Comment by dev7ch** [comment]
I think to watch the input in particular paste function should be possible:

but maybe AngluarJS could help with sth like:

```<input type='text' ng-paste='handlePaste($event.clipboardData.getData('text/plain'))'>```

please double check @TheMaaarc

**Comment by nadar** [comment]
The login form is not written in angular context.

**Comment by nadar** [comment]
@dev7ch can someone confirm this is fixed? so we could close this issue.

**Comment by dev7ch** [comment]
i can confirm, paste and autofill are working fine now in Firefox and should work in other browser as well, so yes.

see https://github.com/luyadev/luya-module-admin/blob/master/src/resources/js/login.js#L106
