### ISSUE TITLE
admin-ngrest-log : The admin log table no  deletion log was recorded. 

### ISSUE THREAD

**Issue by baqianxin** [luyadev/luya-module-admin#102]
and the function eventAfterDelete()  didn't set the value of `attributes_json`.

**Comment by nadar** [comment]
attributes_json has no value on delete in is therefore a bug. thanks

**Comment by nadar** [comment]
@baqianxin fixed in 1.2 (dev-master) and 1.1 branch (pushed 1.1.1.3 patch release).

Thanks!
