### ISSUE TITLE
ngRest model behaviors breaks any DropDown Select

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#104]
Hi!

Assume there are two ngRest models First and Second.

Second model has `first_id` attribute to use it as relation to First.

Adding ngRest plugin `selectModel` works just fine 

```php
/**
 * @inheritdoc
 */
public function ngRestAttributeTypes()
{
    return [
        'description' => 'text',
        'first_id' => [
            'selectModel',
            'modelClass' => First::className(),
            'valueField' => 'id',
            'labelField' => 'title'
        ],
    ];
}
```

unless any Second model behavior defined e.g.

```php
public function behaviors()
{
    return [
        'sluggable' => [
            'class' => SluggableBehavior::className(),
            'attribute' => 'description',
            'slugAttribute' => 'alias',
            'ensureUnique' => true,
        ],
        'timestamp' => [
            'class' => TimestampBehavior::className(),
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
            ],
        ],
    ];
}
```

Module to test to https://github.com/nick-denry/luya-behavior-bug-testmod

Install, test Second model crud and uncomment behavior:

https://github.com/nick-denry/luya-behavior-bug-testmod/blob/34d4d50b3259fb689b7e93950063fb8aaa99e2b4/models/Second.php#L70

The same thing for a SelectArray plugin.

**Comment by nick-denry** [comment]
Works fine if merged with `parent::behaviors();`

**Comment by nick-denry** [comment]
> So we can close the issue?

Technically, yes. 

But as for me this is an unexpected usage of behaviors according to how they are used in ActiveRecord. So, maybe it's need to add a note about this peculiarity to ngRest guide or even use traits instead of behaviors at `luya\admin\ngrest\base\NgRestModel`?

**Comment by nadar** [comment]
i think using behaviors is not wrong if it fits the needs, you just have to call the parent implementation. but this is something which should by done anyhow always even for init(). But maybe adding a hint about this in the docs would be good. would you like to send a PR?

**Comment by nick-denry** [comment]
> i think using behaviors is not wrong if it fits the needs

I'm not sure that I've explain my suggestion well. So try once more. 

Cases:

1. Maybe it's better to replace behaviors at `luya\admin\ngrest\base\NgRestModel` class with traits, so user's sublass of NgRestModel (e.g. generated model) wont need `parent::behaviors();`. This way `behaviors()` would used as `userspace` and not `core` func (nevermind).

or

2. It is just enough add a hint to the guide that `parent::behaviors();` needed.

So I'm not tell that using behaviors is a bad thing.

What case do you prefer? I would like to send a PR of course.

**Comment by nick-denry** [comment]
And I don't realize what do u mean about `init()`.

**Comment by nadar** [comment]
1. sorry i have over seen this. Sadly we can not use traits as the attached ngrestEventBehavior is using the ngrest model events (https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/NgRestModel.php#L62-L65) - https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/NgRestEventBehavior.php#L44 

So we have to call parent implementation of behaviors() - and this is also very known when using init(), you always should call parent implementation (like this: https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/Api.php#L58)

**Comment by nick-denry** [comment]
Call of `parent::behaviors()` not the same as simple call of the `parent::init()` because `behaviors()` always return an array.

A code for user's ngRest model should looks like:

```php
public function behaviors()
{
    $parentArr = parent::behaviors();
    $currentArr = [
        'sluggable' => [
            'class' => SluggableBehavior::className(),
            'attribute' => 'description',
            'slugAttribute' => 'alias',
            'ensureUnique' => true,
        ],
        'timestamp' => [
            'class' => TimestampBehavior::className(),
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
            ],
        ],
    ];
    return array_merge($parrentArr, $currentArr);
}
```

it's not the same simple as just `return <array>` for `behaviors()`.

So maybe it's better to add something like `ngRestBehaviors()` function to use bevariors more transparently:

User's `ngRest` model:

```php
/**
 * Behaviors as ususal.
 */ 
public function ngRestBehaviors()
{
    return [
        'sluggable' => [
            'class' => SluggableBehavior::className(),
            'attribute' => 'description',
            'slugAttribute' => 'alias',
            'ensureUnique' => true,
        ],
        'timestamp' => [
            'class' => TimestampBehavior::className(),
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
            ],
        ],
    ];
}
```

And `luya\admin\ngrest\base\NgRestModel` class:

```php
/**
     * @inheritdoc
     */
    public function behaviors()
    {
        $classBehaviors = [
            'NgRestEventBehvaior' => [
                'class' => NgRestEventBehavior::className(),
                'plugins' => $this->getNgRestConfig()->getPlugins(),
            ],
            'LogBehavior' => [
                'class' => LogBehavior::className(),
                'api' => static::ngRestApiEndpoint(),
            ],
        ];
        return array_merge($classBehaviors, $this->ngRestBehaviors());
    }

     /**
      * @inheritdoc
      */
     public function ngRestBehaviors()
     {
         return [];
     }
```

**Comment by nick-denry** [comment]
And maybe `ngRestBehaviors()` is not good idea, cause user still available to call `behaviors()` directly and break the parent one.

**Comment by nadar** [comment]
> It's not the same simple as just return <array> for behaviors().

Yes i agree, you are right. Returning the array and merging the parent is more pain then just call parent implementation.

> And maybe ngRestBehaviors() is not a good idea, cause user still available to call behaviors() directly and break the parent one.

Yes i thought the same `ngRestBehaviors()` would not change anything.

What we could is attaching the behaviors in the class __constructor like 

```php
public function __construct($config = [])
{
    $this->attachBehaviors(..)
   // https://www.yiiframework.com/doc/api/2.0/yii-base-component#attachBehaviors()-detail

   return parent::construct($config);
}
```

This should attache the behaviors accordingly and behaviors() can be called without parent implementation.

**Comment by nick-denry** [comment]
Awesome. I've totally forgot about `attachBehaviors()`.
Made a PR https://github.com/luyadev/luya-module-admin/pull/106 so you could close this issue if PR is OK.

**Comment by nadar** [comment]
@nick-denry i am going to close this issue as we have a pull request with an on going discussion about how to prevent this problem in future.
