### ISSUE TITLE
DB Migration fails on MySQL with utf8mb4 encoding

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-module-admin#109]
```
*** applying m161220_183300_lcp_base_tables
    > create table admin_proxy_machine ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: CREATE TABLE `admin_proxy_machine` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` varchar(255) NOT NULL,
	`access_token` varchar(255) NOT NULL,
	`identifier` varchar(255) NOT NULL UNIQUE,
	`is_deleted` tinyint(1) DEFAULT FALSE,
	`is_disabled` tinyint(1) DEFAULT FALSE
)
```

The problem is about the UNIQUE index on the `identifier` field.
Column length of 255 chars fits into 767 when the maximum lenght of a char is 3 byte (mysql utf8 encoding) in utf8mb4 it is 4 bytes per character so it exceeds the maximum key length.

What is `identifier`? does it need to be 255 chars long or is a smaller value suffcient?

The same seems to apply to `build_token` in table `admin_proxy_build` in the same migration file.

**Comment by nadar** [comment]
Thanks!
