### ISSUE TITLE
Conditional select in admin CRUD

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya-module-admin#113]
Possibility to show specific input field based on select option !

For example : 

<img width="977" alt="screen shot 2018-05-03 at 11 39 12" src="https://user-images.githubusercontent.com/3844254/39569861-c1034e48-4ec6-11e8-9913-3ef7bdc3e8b9.png">

If the image option is selected in the dropdown list, only the image field is shown

**Comment by nadar** [comment]
@JDL747 i just pushed a idea to solve the problem, you can now define a `condition` key for every ngrest attribute definition. See the comment, let me know if this works as expected.

**Comment by dven84** [comment]
Is it possible to use this for blocks? This would be very useful.

**Comment by nadar** [comment]
@dven84 no, we have to rewrite the whole block configuration system so we can make use of this to! But we will, as its planed.

**Comment by tufailkhan215** [comment]
can we use this condition logic for blocks so we could poplulate fields or value of other fields based on the value of another field

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/issues/113#issuecomment-387024848
