### ISSUE TITLE
Editing a file does not show full form on smaller screen

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-module-admin#114]
overflow: auto is missing.

![bildschirmfoto von 2018-05-04 10-25-59](https://user-images.githubusercontent.com/189796/39618787-9a7de732-4f85-11e8-8cac-9c5b45e25530.png)

**Comment by nadar** [comment]
@cebe this should be fixed in the latest dev-master (since yesterday), could you give the ^1.2@dev a try? (https://github.com/luyadev/luya-module-admin/issues/111)

**Comment by nadar** [comment]
(maybe also use dev-master for cms module, as we have to switch to strict dependency injection in angular code. Releases are very close.)

**Comment by cebe** [comment]
seems to be fixed in dev-master.
