### ISSUE TITLE
Feature Request: Show block preview on hover menu

### ISSUE THREAD

**Issue by dven84** [luyadev/luya-module-admin#120]
Like preview in file manager. 
![screenshot_37](https://user-images.githubusercontent.com/10542161/39875724-d85bf512-548a-11e8-94c1-9c36065374a8.png)
![screenshot_13](https://user-images.githubusercontent.com/10542161/39875725-d88133c2-548a-11e8-985d-331cb01b0c34.png)

**Comment by nadar** [comment]
Yes, i really like this. We where thinking about this too of course, but the problem is: what would you like to display? The only solution would be to provide a static path to a "preview image" in the block.

(ps: have to move the issue to luya-module-cms as its related to the cms)

**Comment by dven84** [comment]
> The only solution would be to provide a static path to a "preview image" in the block.

I agree. Maybe with the same name as the block and in the same folder.

**Comment by nadar** [comment]
It would be cool to auto generate those screenshots. For example we could use a service which makes a screenshot for page with a selector.

https://urlbox.io/docs for example, with the option selector. 

This way you could change the css of any block and the screenshot would be refreshed by itself.

**Comment by nadar** [comment]
Or maybe even something like this! https://github.com/niklasvh/html2canvas
