### ISSUE TITLE
Displaying version of Luya

### ISSUE THREAD

**Issue by arollmann** [luyadev/luya-module-admin#148]
It could be interesting to show version number of each installed core module in the dashboard, so we could easily verify if upgrade is possible/needed.

**Comment by nadar** [comment]
You can enable developer mode (in user profile) and see all installed packages with the according release.

**Comment by arollmann** [comment]
Aw, sorry, didn't see this little checkbox…
Thanks for reply and for all the good work.
Closing this issue.

**Comment by nadar** [comment]
If you have mutliple luya website you can track all those informations with the luya remote admin module.

https://luya.io/packages/luyadev--luya-module-remoteadmin

**Comment by arollmann** [comment]
Oh yes.  Really fine.  Thx.

**Comment by arollmann** [comment]
Regarding the multi-sites : is there a possibility to install LUYA properly to manage multiple websites (as in Yii 2 Advanced Template : one vendor dir/multiples websites) ?  What would be the best practice ?

**Comment by nadar** [comment]
What do you mean by `one vendor dir/multiples websites`. I think the vendor folder should be depending on the website, as it may have different dependencies. Could you please tell me more what you like to do? Multiple domains for the same website?

**Comment by arollmann** [comment]
I mean multiple sites with different root directories and different (sub)domain names, but with the same admin module, the same CMS,  the same team of users/content writers and the same DB. I'm used to doing it with the Yii Advanced template : one backend, multiple frontends.

**Comment by arollmann** [comment]
Any idea about this ?

**Comment by nadar** [comment]
Sorry @arollmann i forgot about this one. The question is, are you using CMS or not? because you don't need different application folders as its all stored in database page?

**Comment by nadar** [comment]
We never had such a request for a page. If you have multiple domains you can just assign them to one luya instance and then display hide different content based on current server url.

What you also can do is mapping different domains to different languages (hostInfoMapping): https://luya.io/guide/concept-composition

**Comment by nadar** [comment]
What you could do as well, is of course using luya headlesss - but this is still in development: https://github.com/luyadev/luya-headless

So you can manage the content in the admin, but access the content for given side trough api, this will be the future of webdevelopment anyhow :smile: (hopefully)
