### ISSUE TITLE
How to display data from reference table?

### ISSUE THREAD

**Issue by kizzna** [luyadev/luya-module-admin#153]
How to reference to related table's column name?

I performed following steps: 

1. Create DB tables:
DB Table 1: test_country
- id : primary key / country_name
DB Table 2: test_city
- id : primary key / city_name / country_id (fk points to test_country : id)
- inserted USA / France / Thailand to test_country
- inserted 2 cities per country on test_city

2. Generate module test with luya module/create

3. generate crud for both country and city with luya admin/crud

4. change config file to include testadmin

5. added following codes in City.php
public function extraFields()
    {
        return ['country_name'];
    }

    public function getCountry_name() {
        return $this->hasOne(Country::class, ['id' => 'country_id']);
    }

    public function ngRestExtraAttributeTypes()
    {
        return [
            'country_name' => 'text',
        ];
    }

    // ngRestScopes()
    ['list', ['city_name', 'country_name']],

6. calling ...testadmin/city/index shows data as follow
ID	City Name			Country Name	
1 	Sitka 				{"id":1,"country_name":"USA"} 	
2 	Los Angeles 		{"id":1,"country_name":"USA"} 	
3 	Paris 				{"id":2,"country_name":"France"} 	
4 	Reims 			{"id":2,"country_name":"France"} 	
5 	Bangkok 			{"id":3,"country_name":"Thailand"} 	
6 	Nakhon Ratchasima 	{"id":3,"country_name":"Thailand"} 	

how to get to test_country.country_name instead of whole records as json here?

**Comment by nadar** [comment]
Maybe try this:

```php
public function ngRestExtraAttributeTypes()
{
return [
'country_name.country_name' => 'text',
];
}
```

Maybe rename your relation to `getCountry` instead of `getCountry_name` so it would be `country.country_name` - not sure if it works, let me know if not, so will do some research as its a very common scenario.

**Comment by kizzna** [comment]
Thanks @nadar 

Following code worked.

```php
`public function genericSearchFields()
    {
        return ['city_name'];
    }

public function extraFields()
    {
        return ['**country**'];
    }

public function getCountry() {
        return $this->hasOne(Country::class, ['id' => 'country_id']);
    }

public function ngRestExtraAttributeTypes()
    {
        return [
            '**country.country_name**' => 'text',
        ];
    }

public function ngRestScopes()
    {
        return [
            ['list', ['city_name', '**country.country_name**']],
            [['create', 'update'], ['city_name', 'country_id']],
            ['delete', false],
        ];
    }`
