### ISSUE TITLE
Excel export: Convert date/time fields into readable form

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#170]
It would be great if the generic Excel export could recognize date/datetime/time fields and convert them into a readable format like JJJJ-MM-TT hh:mm:ss

**Comment by nadar** [comment]
The export modal should have to options: raw or formatted

+ raw returns the value from database
+ formatted returns values trough defined ngrest attribute list (if available, otherwise raw)

**Comment by nadar** [comment]
```php
public function ngRestExportFormatter()
{
    return [
        'is_cancelled' => 'bool',
        'created_at' => 'datetime',
        'cat_id' => function($model) { return $model->cat->title; }
    ] 
}
```
