### ISSUE TITLE
Custom ngrest view file

### ISSUE THREAD

**Issue by baqianxin** [luyadev/luya-module-admin#173]

**Comment by nadar** [comment]
@baqianxin could you please add a description of what you try to do, or how we could achieve your goal. We spent a lot of time helping people, improve the system, building the system. So i am sure you will also have the time to add a proper description.

**Comment by baqianxin** [comment]
RestCurd has no module  , did not use the useAppViewPath parameter
@nadar Hi
I want to customize the _crudform file, can I modify this method?
https://github.com/baqianxin/luya-module-admin/blob/11ff9381ce34dbe66d1eac58b8506ed883266a2a/src/ngrest/render/RenderCrud.php#L50-L53
https://github.com/baqianxin/luya-module-admin/blob/11ff9381ce34dbe66d1eac58b8506ed883266a2a/src/views/ngrest/crud.php#L221-L227

**Comment by baqianxin** [comment]
```
        if ($this->module instanceof Module && $this->module->useAppViewPath) {
            return '@app/views/'.$this->module->id.'/'.$this->id;
        }    
        return parent::getViewPath();
```

**Comment by nadar** [comment]
We only want to provide things to configure which makes sense for the future, configuring the view files to override makes no sense to me. This view file can change within the next release, so you wont be able to update your system anymore, this is definitely a philosophy we don't share.

I will leave this issue open for discussion (@luyadev/core, @luyadev/maintainer).

**Comment by TheMaaarc** [comment]
I can only agree with @nadar.

@baqianxin If you want to change the crud views, propose your changes in a new issue (or multiple issues if the changes don't correlate) and we can discuss them. Maybe we will integrate them completly, adapt some ideas or just expand the current crud to allow for specific changes in the overall view.

**Comment by baqianxin** [comment]
or  like this:
```
 'jsonData'=> function(){
    return render('view')
}
```

**Comment by baqianxin** [comment]
![image](https://user-images.githubusercontent.com/6780391/42493956-6f074750-8451-11e8-9abf-b49644374530.png)

**Comment by baqianxin** [comment]
that part is a field content

**Comment by nadar** [comment]
You can use "condition" in order to show/hide fields or a given set of fields. see https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/Plugin.php#L58-L76
