### ISSUE TITLE
Dependent SELECT fields feature

### ISSUE THREAD

**Issue by Webkadabra** [luyadev/luya-module-admin#178]
It'd be nice to have a way to create dependent SELECTs and AUTOCOMPLETE.

For example, there are 3 SELECT elements: SELECT country_ID, SELECT region_id, SELECT city_id. 
When user chooses COUNTRY_ID - I'd like to update list of options in REGION SELECT, and when region is selected - update options in CITY select. 

It would be really great not to load all `city` options on page load, as it may have somewhere from 20k records up to many thousands for huge app.
 
ALSO, I'd like to add `autocomplete` field for `street_id`, and this autocomplete must become available/active only when all three above selects are filed in, and make this AUTOCOMPLETE search at endpoit like `/admin/api-street-id/?city_id=123`, where `123` is `city_id` from city_id SELECt value.

I mean it's easy to do it in yii2/jQuery UI, but I'm so new to the angularJS I'm not as capable :1st_place_medal:

**Comment by nadar** [comment]
We have an issue with a concrete implementation plan => https://github.com/luyadev/luya-module-admin/issues/298
