### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#191]
New global solution for pagination:

+ CRUD
+ Filemanager

Current filemanager

![image](https://user-images.githubusercontent.com/3417221/43126860-397f33f8-8f2e-11e8-8494-789fdb1d6067.png)

Current Crud:

![image](https://user-images.githubusercontent.com/3417221/43126878-4716c968-8f2e-11e8-9153-95298fd7f618.png)

**Comment by nadar** [comment]
The `Slider Pagination Concept` looks like a very perfect solution to me!

**Comment by nadar** [comment]
Maybe including a `go to first` and `go to last` page, but then this looks perfect to me.

**Comment by TheMaaarc** [comment]
Something like this? I don't know if we actually need a go first / last because you can easily drag it to the start or end (the crud will only be reloaded once the user stops dragging).

![screen shot 2018-07-24 at 15 48 30](https://user-images.githubusercontent.com/3450438/43142611-195ba306-8f59-11e8-983f-1b51629db0ec.png)

**Comment by TheMaaarc** [comment]
Maybe an indication how many pages there are: 0 ––––– 300

But I'll implement that right away without designing it.

**Comment by nadar** [comment]
What if there are only 3 pages? Then it should be easy - large - steps to go to the next page. What i mean is: the "line" should always have the same width but the distances between steps should be large/smaller:

3 pages: 1----------2----------3
10 pages 1-2-3-4-5-6-7-8-9-10

You know what i mean?

But looks good the me your first draft! Looking forward to see this in action. I will try to make a general directive.

**Comment by TheMaaarc** [comment]
![https://goo.gl/XNWV16](https://lh3.googleusercontent.com/KMfMomv6aGfZQabqjHbHwN1IwXWNxw-u7CM_FOGOtVLB7KTH_3K6PxFbTukyScokipKjCIdLG0yMxfLERXeg=w2560-h1333-rw)
