### ISSUE TITLE
Filemanager: Forget file selection when changing active directory

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#194]
When selecting files in the filemanager and then clicking on another directory, the files stay selected, although they are no longer visible. It would be better to forget/reset file selection when changing directories (as one might easily delete the wrong files).

![filemanager selections](https://user-images.githubusercontent.com/3786245/43462253-e4aca4f2-94d5-11e8-9cf0-c5f2f2660911.gif)

**Comment by nadar** [comment]
Sure we can reset the selected files when switch to another folder.
