### ISSUE TITLE
Feature request: Manual image cropping with filters

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#196]
When applying a filter to an image that results in image cropping, there is currently no way to manually define the cropping area. There could be a button next to the filter dropdown with a cropping icon that opens a cropping dialog. There are a number of JavaScript libraries for this purpose:

https://ourcodeworld.com/articles/read/281/top-7-best-image-cropping-javascript-and-jquery-plugins

The aspect ratio of the cropping zone would have to be fixed according to the filter settings.

**Comment by nadar** [comment]
we should avoid using jQuery. It must be: pure angularjs code or native javascript code.

**Comment by nadar** [comment]
maybe something like this? https://github.com/CrackerakiUA/ui-cropper

**Comment by rolandschaub** [comment]
Yes, this looks good.

**Comment by nadar** [comment]
+ add "edit" button in file detail
+ create a copy of the file
+ apply changes
+ if "replace" original is select, replace the original file and remove all filter versions

**Comment by nadar** [comment]
https://github.com/CrackerakiUA/ui-cropper
