### ISSUE TITLE
Broken TimePicker in News section

### ISSUE THREAD

**Issue by buttflattery** [luyadev/luya-module-admin#2]
- OS Information: Windows 10 Pro
- System Type: 64-bit OS x64-based Processor
- Browser Info: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Browser Info : Firefox 57.0 (64-bit)

Demo seems to be broken at some sections like if you go to `admin` and try to create a `new news` and then select `Date` under `time` section the `timepicker` appears after selecting `date` but clicking it wont do anything and the layout seems to be broken as the hours and minutes are not aligned. The layout, it acts differently in both `Chrome` and `Firefox`  although the `timepicker` does not work under both of them the layout seems to be ok in `chrome` but not in firefox here are the screen grabs for both the browsers

`FIREFOX`

![image](https://user-images.githubusercontent.com/1536454/33958024-28f549a0-e065-11e7-9368-b25cd94bb205.png)

`CHROME`

![image](https://user-images.githubusercontent.com/1536454/33958053-38e631c6-e065-11e7-9b11-31b7dc67569c.png)

**Comment by nadar** [comment]
@buttflattery Okay thanks for the report. Actually there is no time picker so far :-)

**Comment by buttflattery** [comment]
ahh Ok! I thought that there is the icon of the clock so assumed there would be a timepicker that is missing.

**Comment by nadar** [comment]
@buttflattery Well, what you are saying is truly a user experience problem, an icon which promise something like the calendar does for the date. Thanks for the input.
