### ISSUE TITLE
Escape filter name

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#201]
When using the command to create a filter, the filter's name entered by the user should be escaped. Otherwise it can lead to errors like this:

```php
public function name()
{
    return 'Volle Breite HD (1'200 Pixel)';
}
```

The problem is the ' in 1'200.

**Comment by nadar** [comment]
@rolandschaub But this will trigger an php exception..?

'Crop large (\'800x800\')'

**Comment by rolandschaub** [comment]
I mean:

```php
public function name()
{
    return 'Volle Breite HD (1\'200 Pixel)';
}
```
