### ISSUE TITLE
 specify whether to check the MIME type when the file is uploaded.

### ISSUE THREAD

**Issue by baqianxin** [luyadev/luya-module-admin#207]
https://github.com/luyadev/luya-module-admin/blob/49d83f95929ccb3f61dd22babdb2bc16912f7040/src/storage/BaseFileSystemStorage.php#L423-L447

* add check mime type = false
* add whiteListExtensions =[....]
* amend File plugin support for specifying upload file types

**Comment by baqianxin** [comment]
@nadar :smiley:

**Comment by nadar** [comment]
@baqianxin does the introduced property work? can we close the issue?
