### ISSUE TITLE
Unable to extend \luya\admin\ngrest\plugins\SelectModel

### ISSUE THREAD

**Issue by pivans** [luyadev/luya-module-admin#215]
Exception 
`file: "/vendor/luyadev/luya-module-admin/src/ngrest/plugins/SelectModel.php",`
`line: 137,`
`message: "Cannot access property MyPluginExtendSelectModel::$_dataInstance"`

php: 7.1

**Comment by nadar** [comment]
Could you please post the whole code how you are integrating the select model?

**Comment by nadar** [comment]
@pivans we never had the case where someone wanted to extend from such a plugin, why would you do that? so if i understand your use case maybe we can improve this even more.
