### ISSUE TITLE
Edit system config: Name not visible

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-admin#221]
See GIF for more informations:

![2018-10-08 12 44 39](https://user-images.githubusercontent.com/3450438/46604933-1c484a80-caf8-11e8-8d47-d95165c88896.gif)

**Comment by nadar** [comment]
@TheMaaarc yes i agree, makes sense to display this column.

**Comment by nadar** [comment]
Now i've seen the problem, sorry. Seems to be a problem with the zaa-slug directive.
