### ISSUE TITLE
Cache and image filter

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#224]
Since latest version when applying an image filter (for example as image cms page property) the filter version of the image is created successfull, but the cache for the storage component is not cleared and therefore the new image filter verison is not available in the frontend until the cache reload button is triggered.

**Comment by martinpetrasch** [comment]
Another bug report:
1. Create image block (I'm assuming with cache enabled)
2. Choose image and filter
3. There is no image in CMS view and frontend but if you check the block again the image and filter settings are still there
4. But after hitting the the reload button in CMS you'll see the image.

**Comment by nadar** [comment]
@martinpetrasch could you please try with latest admin dev-master?

**Comment by martinpetrasch** [comment]
I tried and it works now! Thanks for the fix!
