### ISSUE TITLE
Filemanager default behaviour (download/show)

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-admin#225]
It would be nice if we could define a default behaviour for all files.  
Currently we can change the behaviour (download/show file) on a per file basis in the Filemanager.

For me personally, a config option in the module would be enough. Something like this:

```
'admin' => [
    'defaultFileBehaviour' => 'download'
]
```

**Comment by nadar** [comment]
The problem with the default behavior is that we could only override every file delivery, which means if this is defined the user could not change the behavior of a single file. (As we only have a boolean field which indicates the status of file disposation: inline_disposition)

**Comment by nadar** [comment]
As discussed with @rolandschaub, we are going to introduce this property, but its just the default value for upcoming uploaded files.
