### ISSUE TITLE
File Manager doesn't remember page when reopening

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#234]
When the file manager is opened, it doesn't remember on what page it was beforehand. E.g. if I open the file manager and go to page 2 of a paginated list, close the file manager and then reopen it, it will show page 1. This is annoying when selecting several individual files e.g. in a block.

**Comment by nadar** [comment]
@rolandschaub this very hard to implement, but can be done.

**Comment by rolandschaub** [comment]
@nadar okay, great, it would make the file selection process much more user friendly.

**Comment by rolandschaub** [comment]
Additionally, the file manager should also remember the last sorting order.
