### ISSUE TITLE
Feature request: Multiple menu entries and CRUD view for same models / data pools

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#236]
There are situations where it would be useful to have multiple menu items and CRUD views to edit data from the same model and database table, filtered by rule(s). One way to do this would be the use of data pools, represented by a pool_id field in the models and tables that support the feature.

**Comment by nadar** [comment]
![IMG_20190318_091243](https://user-images.githubusercontent.com/3417221/54930595-d3eede80-4f17-11e9-898f-f5c7db472add.jpg)

+ menu points can have a context definition like `context_field = pool_id` and `context_value = 1`.
