### ISSUE TITLE
zaa-link: logout when changing to file with previously defined external URL

### ISSUE THREAD

**Issue by martinpetrasch** [luyadev/luya-module-admin#243]
1. use zaa-link in block
2. set external url and save
3. set to file -> logout

**Comment by nadar** [comment]
@martinpetrasch could you please provide the XHR requests which forces the logout?

**Comment by martinpetrasch** [comment]
Request URL: /admin/api-admin-storage/file-info?id=https://www.google.com
Request Method: GET
Status Code: 403 Forbidden

**Comment by nadar** [comment]
@martinpetrasch what version of LUYA are you using? Cause on latest dev-master it throws an http not found exception instead of a forbidden exception.

**Comment by martinpetrasch** [comment]
It was on dev-master but not updated until today. Thanks for the fast fix!
