### ISSUE TITLE
facing issues while using with postgres

### ISSUE THREAD

**Issue by tufailkhan215** [luyadev/luya-module-admin#244]
i have made a site using mysql but then i have to transfer to postgres as bolean used there was giving error i have changed it manually to smallint but now the admin do not work properly and giving this error
TypeError: "n(...)(...)[0] is undefined"
controllerhttp://192.168.25.49/public_html/inx-rms/assets/8c7c310d/dist/js/main.uglified.js:1:4479invokehttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:44:458gethttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:95:161phttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:70:1iahttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:81:321khttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:137:396digesthttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:148:370applyhttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:152:239khttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:103:283shttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:108:386onloadhttp://192.168.25.49/public_html/inx-rms/assets/3d7e18a3/dist/js/main.js:109:300

**Comment by nadar** [comment]
Could you please provide the xhr response which is (or even not) correctly typecased and therefore the angular directive has an exception.

**Comment by nadar** [comment]
I am going to close this as informations are missing, please re open if the problem persists or information is available.
