### ISSUE TITLE
user sortable main menu

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#262]
The user should have the possibility to sort the main menu (menu bar left) by its own. The information is stored in user data json.

Maybe a drag and drop sorting would be nice - maybe its also overkill.

+ drag'n'drop: Where should be add this icon? 
![image](https://user-images.githubusercontent.com/3417221/51526879-9d231c00-1e33-11e9-9223-bb561cfd5aa4.png)
+ or its part of user settings sections:

![image](https://user-images.githubusercontent.com/3417221/51526898-ab713800-1e33-11e9-84c7-47cce98debbc.png)

**Comment by dev7ch** [comment]
> or its part of user settings sections

would it make more simple and easier to implement flexibility.

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
