### ISSUE TITLE
Datepicker: Highlight today's date

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#263]
It would be helpful to see today's date in the date picker. There is no visual indication that today is January 22, 2019 in the datepicker:

![datepicker](https://user-images.githubusercontent.com/3786245/51547879-6e269d80-1e67-11e9-939d-69677a1479bb.png)

**Comment by nadar** [comment]
https://github.com/720kb/angular-datepicker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+today

**Comment by nadar** [comment]
If we want to fix this, we have to add our own solution...
