### ISSUE TITLE
Idea for Assistant for first login in Admin panel

### ISSUE THREAD

**Issue by testt23** [luyadev/luya-module-admin#266]
Hi, I have idea for LUYA Assistant for first login in Admin panel

I can added in my admin panel , see example;
![3](https://user-images.githubusercontent.com/3694008/51790125-ed82dc80-2199-11e9-9fc8-ccca4280278b.png)
![4](https://user-images.githubusercontent.com/3694008/51790126-ed82dc80-2199-11e9-9d65-725527dee3a5.png)
![8](https://user-images.githubusercontent.com/3694008/51790127-ee1b7300-2199-11e9-8204-019617f71f38.png)
![1](https://user-images.githubusercontent.com/3694008/51790128-ee1b7300-2199-11e9-8772-1abca43c8777.png)

**Comment by TheMaaarc** [comment]
I like the idea too. The easiest way to implement it would be to use an already existing library like https://introjs.com/ for example.

I agree with @nadar that we should start with some basic stuff.  
@nadar maybe a module should be able to add "steps" to the guide via a config file? Maybe we can than add a tour per module in the profile section – or just a "big tour" that goes through admin, cms and any other module that has those steps configured.

A "step" looks like this (example taken from introjs):
```
{
    element: document.querySelectorAll('#step2')[0],
    intro: "Ok, wasn't that fun?",
    position: 'right'
}
```

We wouldn't use `element` with `document.querySelectorAll` but with a ID that would have to be unique.

With `introjs` we would have to find a solution to change "pages" in angular, maybe we could incorporate that in a [`onbeforechange` function](https://introjs.com/docs/intro/api/#introjsonbeforechangeprovidedcallback) or something like that.

**Comment by testt23** [comment]
I can used this https://introjs.com/

My idea is what the colleague asp offers. There is a basic circumference and then each module has a configuration for the assistant. This facilitates the management of the assistant. it is organized.

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
