### ISSUE TITLE
Possibility to rename files

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#27]
In the file manager it should be possible to rename files.

**Comment by nadar** [comment]
Styling of edit mode

![image](https://user-images.githubusercontent.com/3417221/39433718-dd2dd5b6-4c96-11e8-9cd1-0331229d5a64.png)

**Comment by nadar** [comment]
Maybe same still as when in display mode:

![image](https://user-images.githubusercontent.com/3417221/39433757-f9627840-4c96-11e8-89c9-ee09ab851360.png)

just with none block input text.
