### ISSUE TITLE
How to install "LUYA Administration Interface module"  for windows

### ISSUE THREAD

**Issue by mazgiii** [luyadev/luya-module-admin#274]

**Comment by mazgiii** [comment]
how to install "LUYA Administration Interface module"  for windows

**Comment by mazgiii** [comment]
php index.php migrate not working

**Comment by nadar** [comment]
If you report a bug on GitHub you should provide as much infos as need - this is also described in the template you saw when creating the issue. We can not help or find a bug unless you have provided as much info as possible.
