### ISSUE TITLE
zaa-radio Initvalue

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-admin#284]
It should be possible to set an "initvalue" [(like the one for zaa-select)](https://luya.io/guide/app-block-type-select) for the zaa-radio plugin.

**Comment by nadar** [comment]
The initvalue would be: 1/0 which means checked or not, i assume.

**Comment by TheMaaarc** [comment]
No. The zaa-radio plugin has multiple options and not just a 1/0 state.

It's exactly like the zaa-select plugin.

**Comment by nadar** [comment]
yes indeed, i messed up with `checkbox`.
