### ISSUE TITLE
Google 2FA

### ISSUE THREAD

**Issue by davidtim** [luyadev/luya-module-admin#287]
Hello, do you have any plan to use Google 2FA with login?

**Comment by nadar** [comment]
We have an issue about YubiKey integrations #22, but in general, yes we are always interested in improve security or provide more security options.

**Comment by nadar** [comment]
@davidtim if you have any suggestions, SDKS, examples or something else in how to integrate google 2FA, please post it here.

**Comment by davidtim** [comment]
@nadar I suggest this https://github.com/2amigos/yii2-usuario/blob/master/docs/helpful-guides/how-to-implement-two-factor-auth.md

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/issues/22

**Comment by nadar** [comment]
https://github.com/RobThree/TwoFactorAuth
