### ISSUE TITLE
Files Manager: Should remember sorting order

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#290]
The File Manager doesn't remember the sorting order of the files listing. Example:

- go in File Manager to a specific folder and sort files by creation date
- go to another LUYA section
- come back to File Manager: the selected folder is remembered, but the files are sorted by name, which is the default

**Comment by nadar** [comment]
contained as comment https://github.com/luyadev/luya-module-admin/issues/234
