### ISSUE TITLE
API Request Insight

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#293]
It should be possible to have a logger option for API users, this can be turned off or on. If enabled it will log all requests in a table and show metrics about request time and number of requests. An Active Window would provide those insights.

**Comment by nadar** [comment]
+ Add translations
+ Check for text improvements @rolandschaub

**Comment by rolandschaub** [comment]
- "It's not recommended" with "It's" instead of "Its".
- "is currently active" with "active" instead of "activ".
- "Fetch Data" with capital "D" (as with the other buttons).
Otherwise okay.
