### ISSUE TITLE
File List Preview not working

### ISSUE THREAD

**Issue by buttflattery** [luyadev/luya-module-admin#3]
- OS Information: Windows 10 Pro
- System Type: 64-bit OS x64-based Processor
- Browser Info: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Browser Info : Firefox 57.0 (64-bit)

In the `Add News` section where we provide the 

- Image
- Image List
- File List

Under `Media` section the 3rd section i.e `File List` Never shows file preview no matter how many times you provide the file the behavior is same in both `chrome` and `Firefox` see below

`Chrome`

![image](https://user-images.githubusercontent.com/1536454/33958421-2fa22c36-e066-11e7-951d-7e690bdc5bf6.png)

**Comment by nadar** [comment]
@buttflattery Only images provide previews, files never have a preview as it could be everything.

**Comment by buttflattery** [comment]
Well, i guess in that case you are good to close this issue.
