### ISSUE TITLE
SelectModel valueExisitsInOptions issue

### ISSUE THREAD

**Issue by rochdi80tn** [luyadev/luya-module-admin#306]
In valueExisitsInOptions functions we should use `item[$scope.optionsvalue] `and not `item.value `to compare to the given value
This issue will be visible if we use a different value key other than `value`

`zaa.directive("zaaSelect", function() {
`
https://github.com/luyadev/luya-module-admin/blob/62fe9c2066ecd580a9384a6a77530665b0239e0b/src/resources/js/directives.js#L1418

**Comment by nadar** [comment]
Yes, i agree. Would you like to send a PR?

**Comment by rochdi80tn** [comment]
@nadar Seems that it happens you had just committed a change to directives.js causing a conflict with my pull request

**Comment by nadar** [comment]
its not a problem, i can resolve conflicts while merging - or create a new one.
