### ISSUE TITLE
Key <-> Value directive

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#312]
A key value based directive like text array but with the option to define the key. This is very useful when define a basic json.

**Comment by nadar** [comment]
@TheMaaarc We should fix the add button, so maybe it could be next to the input element (to the right).

![Screenshot from 2019-06-19 15-43-25](https://user-images.githubusercontent.com/3417221/59770890-04d97800-92a9-11e9-934f-4118335df539.png)

**Comment by TheMaaarc** [comment]
![Screenshot 2019-06-25 at 11 32 14](https://user-images.githubusercontent.com/3450438/60087400-3f299600-973d-11e9-9ed1-86723e474612.png)

**Comment by TheMaaarc** [comment]
"New key" hat noch keine Translations @nadar

**Comment by nadar** [comment]
:+1:
