### ISSUE TITLE
Schedule option for toggleStatus

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#318]
The ngrest plugin toggleSatus should have the scheduling option like selects.

**Comment by nadar** [comment]
@TheMaaarc In the edit view the scheduler icon should maybe be more close to the checkbox? 

current:

![Bildschirmfoto von »2019-06-24 12-35-10«](https://user-images.githubusercontent.com/3417221/60081445-0c2dd500-9732-11e9-9314-ceacc508176d.png)

**Comment by TheMaaarc** [comment]
@nadar It's not possible to move the crud-loader-button (scheduler) closer to the checkbox because of the current structur/setup of the zaa- plugins.

The crud-loader-button is now horizontally alined with the checkbox.

**Comment by nadar** [comment]
@TheMaaarc now the unit tests are failing for this html structure, would you like to change it or should i?

https://travis-ci.org/luyadev/luya-module-admin/jobs/550197282#L602

**Comment by TheMaaarc** [comment]
Ooops, I'll change it.
