### ISSUE TITLE
Dashboard object sorting

### ISSUE THREAD

**Issue by baqianxin** [luyadev/luya-module-admin#32]
let we can custom the position of  dashboardobjects 

![image](https://user-images.githubusercontent.com/6780391/34507433-cd976df6-f070-11e7-9084-6d319c588f25.png)
exchange position
![image](https://user-images.githubusercontent.com/6780391/34507448-ef5d7a7a-f070-11e7-8741-6182d2b16a53.png)

> Sorry,I've misplaced the picture

**Comment by nadar** [comment]
I am not sure what you mean now:

+ you want to sort the items inside a dashboard object 
+ or you want to rearrange the dashboard items so you can hide and move them left-right-top-down ?

**Comment by baqianxin** [comment]
uh，like this:
![image](https://user-images.githubusercontent.com/6780391/34506508-664eda92-f068-11e7-9d12-00483b690bdf.png)

**Comment by nadar** [comment]
But don't you think this makes only sense wen you have multiple dashboard objects? by now there are only 2 objects by default - not that much to arrange.

**Comment by baqianxin** [comment]
Yes, I just consider when have many chart module

**Comment by baqianxin** [comment]
like this:
![image](https://user-images.githubusercontent.com/6780391/34510992-8abbeb24-f093-11e7-9588-8e2566a87acd.png)

**Comment by nadar** [comment]
Ok. I think we should implement something like this (sort) maybe not that complex i an first step (no draging for example, maybe just arrows or sth like this)

**Comment by baqianxin** [comment]
you are great!

**Comment by baqianxin** [comment]
this is the drag layout(it may be useful):
![image](http://images.shejidaren.com/wp-content/uploads/2017/02/muuri-demo-1.gif)
https://haltu.github.io/muuri/
