### ISSUE TITLE
CRUD view search ineffective after editing and saving record

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#322]
### What steps will reproduce the problem?

Enter a search term in a CRUD view, then edit one of the records and save it.

### What is the expected result?

The CRUD view should still only list the records found by the search.

### What do you get instead? (A Screenshot can help us a lot!)

All records are listed while the search term is still displayed but ignored.

**Comment by nadar** [comment]
It seems this works already
