### ISSUE TITLE
TYPE_DECIMAL within TYPE_MULTIPLE_INPUTS is not being rendered

### ISSUE THREAD

**Issue by mxx-lxg** [luyadev/luya-module-admin#323]
### What steps will reproduce the problem?
Create a block and add a TYPE_MULTIPLE_INPUTS with one or more TYPE_DECIMAL inside of it.

### What is the expected result?
A decimal field should appear in the block properties modal when a new entry is added.

### What do you get instead? (A Screenshot can help us a lot!)
The field is not showing up. In the DOM a zaa-injector tag with no children appears where the field should be.

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

`1: [ini_get('short_open_tag')] '1'
2: [ini_get('error_reporting')] '22527'
3: [phpversion()] '7.1.28'
4: [php_ini_loaded_file()] '/Applications/XAMPP/xamppfiles/etc/php.ini'
5: [php_sapi_name()] 'cgi-fcgi'
6: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'PhpStorm 2018.3.6'`
Had to comment out `apache_get_modules()`, because it threw an undefined error.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0 (admin module 1.2)
| PHP Version      | 7.1
| Platform         | XAMPP
| Operating system | OSX 10.14

**Comment by nadar** [comment]
But does the decimal type works when **not** using in multiple inputs?

**Comment by mxx-lxg** [comment]
Yes. They work fine otherwise.

**Comment by hbugdoll** [comment]
Here is a corresponding Safari error log:
```
[Error] undefined is not an object (evaluating 'e.options.steps')
.../dist/main.js:1 – "<zaa-injector dir=\"opt.type\" options=\"opt.options\" fieldid=\"id-{{msortKey}}-{{mutliOptKey}}\" initvalue=\"{{opt.initvalue}}…"
	(anonyme Funktion) (bower.js:2999)
	Ca (bower.js:2678)
	p (bower.js:2220)
	g (bower.js:1984:241)
	g (bower.js:1984:266)
	(anonyme Funktion) (bower.js:1969)
	(anonyme Funktion) (bower.js:10070)
	(anonyme Funktion) (bower.js:4719)
	$digest (bower.js:4771:193)
	$apply (bower.js:4867)
	(anonyme Funktion) (bower.js:6317)
	dispatch (jquery.js:5430)
```

**Comment by hbugdoll** [comment]
@mxx-lxg you can use the following **workaround** until it will be fixed.
Add an empty `options` key (`'options' => []` or `'options' => null`) along with `TYPE_DECIMAL`:

```
        return [
            'vars' => [
                ['var' => 'plans', 'label' => 'Verträge', 'type' => self::TYPE_MULTIPLE_INPUTS, 'options' => [
                    ['var' => 'minPrice', 'label' => 'Preis pro Minute / SMS', 'type' => self::TYPE_DECIMAL, 'options' => []],
                ]
            ]],
        ];
```
