### ISSUE TITLE
Problem after update (CheckboxRelationActiveQuery)

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-module-admin#329]
### What I did
- Switch admin to ^2.0
- Check / adjust as explained in [UPGRADE.md](https://github.com/luyadev/luya-module-admin/blob/master/UPGRADE.md)
- Switch to CMS ^2.0
- `composer update`
- Check / adjust as explained in [UPGRADE.md](https://github.com/luyadev/luya-module-cms/blob/master/UPGRADE.md)
  - Could not be done through the admin interface as the page didn't event correctly open up
  - Changed the value through SQL

### What is the expected result?
Everything should work as before

### What do you get instead?
```
Error
Maximum function nesting level of '256' reached, aborting!
```

It seems to be related to the CheckboxRelationActiveQuery.
(I don't get any error when commenting the CheckboxRelationActiveQuery related parts) 

### LUYA Check ouput:
```
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] ''
3: [ini_get('error_reporting')] '32767'
4: [phpversion()] '7.2.6'
5: [php_ini_loaded_file()] 'C:\\wamp64\\bin\\apache\\apache2.4.23\\bin\\php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.23 (Win64) OpenSSL/1.0.2p PHP/7.2.6'
```

### Additional infos
| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.18
| LUYA Admin | 2.0.3
| LUYA CMS | 2.0.0
| PHP Version      | 7.2
| Platform         | WAMP
| Operating system | Windows

**Comment by JohnnyMcWeed** [comment]
So my application is using my [service module](https://luya.io/packages/johnnymcweed--luya-module-service), which uses [category](https://luya.io/packages/netfant--luya-category).

Everything worked before updating. Now pages where I was using [teaser block](https://github.com/JohnnyMcWeed/luya-module-service/blob/master/src/frontend/blocks/TeaserBlock.php) are not opening anymore in admin. (Same error as on frontend). Pages where I am using the module aren't showing as well.
Here's the [service model](https://github.com/JohnnyMcWeed/luya-module-service/blob/master/src/models/Service.php), which uses the [checkbox relation plugin](https://luya.io/guide/ngrest-plugin-checkboxrelation).

(I couldn't find any information about adjustments that need to be done in custom modules exept the [strict parsing](https://github.com/luyadev/luya-module-cms/issues/51))

**Comment by nadar** [comment]
So i assume its https://github.com/JohnnyMcWeed/luya-module-service/blob/master/src/models/Service.php#L437-L440 because its referencing itself. Could you try to temporary remove this part so we would know if this is what throws the exception?

**Comment by JohnnyMcWeed** [comment]
It works when removing the fields which are referencing itself from ngRestScopes:
https://github.com/JohnnyMcWeed/luya-module-service/blob/c3609a34ac5b7bfc5a8d30baa61dc0345e34c6b3/src/models/Service.php#L257
`/*'isRelatedTo', 'isSimilarTo',*/`

**Comment by nadar** [comment]
and you are sure it was working with latest major version of luya admin (1.2.3.1)? Cause there where not much changes on this plugin: https://github.com/luyadev/luya-module-admin/commits/master/src/ngrest/plugins/CheckboxRelationActiveQuery.php nor its parent: https://github.com/luyadev/luya-module-admin/commits/master/src/ngrest/plugins/CheckboxRelation.php

**Comment by nadar** [comment]
As the LUYA admin module is cloned with git history into the vendor folder, maybe you could make some research with `git bisect` so we can ensure which commit forced this behavior.

**Comment by JohnnyMcWeed** [comment]
I just installed the kickstarter and the service module... The following config seems to be working.
```
"require": {
        "luyadev/luya-core" : "~1.0.17",
        "luyadev/luya-module-admin" : "~1.2.3.1",
        "luyadev/luya-module-cms" : "~1.0.9",
        "luyadev/luya-bootstrap3" : "~1.0.0",
        "luyadev/luya-generic" : "~1.0.0",
        "johnnymcweed/luya-module-service": "dev-master",
        "netfant/luya-category": "dev-master"
    },
```

**Comment by JohnnyMcWeed** [comment]
I don't know the reason, but it was related to the db as I just found out...

**Comment by nadar** [comment]
What was the problem with the db? Cause the exception says something different.

**Comment by JohnnyMcWeed** [comment]
I know, but I have no idea... xD 
I migrated up the test env I set up before, which was working. (config above)
So then I migrated down and up again the environment where I had the error on update... And then it was working... So I pushed the changes and deployed --> works aswell.
