### ISSUE TITLE
NgRest fields: Adding min-height options to textarea

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-module-admin#33]
It would be nice to have an option in ngRestAttributeTypes(), maybe e.g. like this:

```php
    public function ngRestAttributeTypes()
    {
        return [
            ['info' => ['textarea', 'options' => ['min-height' => '220px']]], 
        ];
    }
```

which lets you define the min-height for textarea inputs in the Admin UI, because now there isn´t much height difference between text and textarea inputs.

**Comment by nadar** [comment]
Well we could add a little more height by default (2-3 visible rows) but otherwise the auto grow textarea makes no sense anymore. But to indicate its a textarea, yes we could add 2-3 rows more by default. Not by option.

**Comment by dev7ch** [comment]
mmh, well yes there is auto grow, but i am not understanding why an option is not good?

e.g..: if you have many textareas in a CRUD it could be good to keep them tight, there adding a min-height option would enable more flexibility in the admin UI crud then setting a fixed value for it.

**Comment by nadar** [comment]
i personally would add a default min-height (but only 2-3 rows, which approx 40px) this indicates textareas more clear which would be a good improvement for users.

I am not against the option, but i think it just makes no sense - yet another configuration. I think its more clever to show all textareas with the same style, this will give the end user a more consistent feeling.

**Comment by dev7ch** [comment]
ok, as you think.
2 - 3 rows are better then it is now i think.

**Comment by baqianxin** [comment]
i english is not very good,but i can understand what you talk about.I think sometimes the textarea shoud has the bigger height.Like this:
![Uploading 20180106211550.png…]()

I implemented it with CSS,
but ,i want custom the class of every block

**Comment by nadar** [comment]
@baqianxin your screenshot seemt not to work.

**Comment by dev7ch** [comment]
@baqianxin there are **block variations** which could help you to add classes in frontend, see https://luya.io/guide/app-blocks

But for admin UI, e.g textarea min-height, it seems there is no solution right now, I like your idea of adding a class to the (block)fields. 

Maybe a `class` option instead of `min-height` is what gives us consistency **and** flexibility, What u think @nadar ?

**Comment by nadar** [comment]
i don't think this would be a good solution. Its just another configuration in the block no one understand. If someone is that advanced to register admin css files, he will also find out how to override all textareas by css.

We should just make the textarea 1-2 rows larger and close the discussion.

**Comment by dev7ch** [comment]
partially agree a little bit, i think everybody would understand `cssClass` or `min-height` and  the "pollution" of the admin UI could be avoided a logic and clear field to provided `options` ( which is excatly there fpr cases like this) but anyhow it looks like this discussion won´t change anything and bring any benefit to luya, a bit sad.

**Comment by baqianxin** [comment]
@dev7ch  I've seen the document of block, and I don't think it's a good way to define block through a configuration file.
```php
'cmsadmin' => [
    'class' => 'luya\cms\admin\Module',
    'blockVariations' => [
        TextBlock::variations()
            ->add('bold-flavor', 'Bold font with Markdown')->cfgs(['cssClass' => 'bold-font'])->vars(['textType' => 1])
            ->add('italic-flavor', 'Italic Font')->cfgs(['cssClass' => 'italic-font'])
            ->register(),
    ]
],
```

**Comment by baqianxin** [comment]
My home network is not very good, can't upload pictures.

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f615.png)

**Comment by nadar** [comment]
Here my answer from above again

> i personally would add a default min-height (but only 2-3 rows, which approx 40px) this indicates textareas more clear which would be a good improvement for users.

> I am not against the option, but i think it just makes no sense - yet another configuration. I think its more clever to show all textareas with the same style, this will give the end user a more consistent feeling.

The most important for me: **this will give the end user a more consistent feeling.**

**Comment by baqianxin** [comment]
ok, how am I to join you

**Comment by dev7ch** [comment]
@nadar is this obsolete and closeable or is maybe 70px min height the holy consisntent min height for the textarea ? ;)
