### ISSUE TITLE
Feature Request: Show public download link to file

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#339]
It would be helpful to see the public download link of a file in the file manager so that it can be copied to link to that file. This should also work with the storage being hosted separately (e.g. on S3).

**Comment by nadar** [comment]
New view including an input field with full url:

![image](https://user-images.githubusercontent.com/3417221/64875003-6b71f600-d64c-11e9-9d56-49880917e52f.png)
