### ISSUE TITLE
When calling Create API, data entry is not matching the data when using admin screen form

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#344]
### What steps will reproduce the problem?
When creating a record using admin forms the data stored in the database in this format
{"en":"example9"}

But when calling the rest api the data stored in the database in this format
example9

So for example when creating a Group in the Addressbook module using the Admin screens
The name field entry saved in the database as
{"en":"Group 1"}

But when creating a Group in the Addressbook module using the api 
"/admin/api-addressbook-group/create"

The name field entry saved in the database as
Group1

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
This is expected, see https://github.com/luyadev/luya-module-admin/issues/279 - if you (as a developer) casting a field as i18n, you are also responsible for providing the i18n data like `['en' => 'example']` instead of `example`. The system can not know where to assigne the language.

**Comment by ifuratdev** [comment]
you are right, that makes sense, i didn't notice the i18n settings
