### ISSUE TITLE
WAF - website application firewall

### ISSUE THREAD

**Issue by testt23** [luyadev/luya-module-admin#348]
what would you say about a similar system that displays attack statistics, false login attempts, which reminds you at intervals of changing your password (to you or your clients) an analysis of attempts to prevent it from hacking through SQLi, xss, RFI, LFI, shell upload and others?  Example https://template.demo.tadgroup.com/admin/

**Comment by nadar** [comment]
Currently we don't have a "user notifications" system, therefore we can not display login attempts. Adding firewall stuff on application level makes no sense for me, unless someone likes to send PR's and work on this. The LUYA team won't work on such things. Feel free to send a PR, so i will close this issue.
