### ISSUE TITLE
selectArray is not saving the value if the value changed to "Nothing selected" 

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#351]
When using selectArray and saving the model with "value 1" for the select.
After that when editing the model and selecting "Nothing selected" by clicking on "X" and saving the model, It will still keep the old value ie "value 1"

example

	public function rules()
	{
		...
			[['status'], 'integer'],   
		...
	}		

	public function ngRestAttributeTypes()
	{
		...
		'status' => ['selectArray', 'data' => static::getStatuses()],
		...	
	}
	public static function getStatuses()
	{
		return [
		    1 => 'Open',
		    2 => 'Win',
		    3 => 'Lost',
		];
	}

If the status is saved with value "Win" and then edited and saved with "Nothing selected", still it will show "Win"

**Comment by nadar** [comment]
Then you have to provide the init value for selectArray or change the isEmpty definition of your integer validation rule as `null` won't be valid.

**Comment by nadar** [comment]
I have added a guide section for you: https://github.com/luyadev/luya/blob/master/docs/guide/ngrest-plugin-select.md#handling-null-empty-values

**Comment by ifuratdev** [comment]
works perfectly, Big thanks

**Comment by nadar** [comment]
welcome
