### ISSUE TITLE
Empty Attribute Group shown if no attributes in the Attribute Group

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#356]
When creating attribute group and the attribute group contains no attributes for some scopes then empty container is shown

Example:
For the Addressbook 
Below is the ngRestScopes defintion

    public function ngRestScopes()
    {
        return [
            ['list', ['group_id', 'salutation', 'firstname', 'lastname', 'street', 'zip', 'city', 'country', 'email', 'notes']],
            [['create'], ['group_id', 'salutation', 'firstname', 'lastname', 'email', 'notes']],
            [['update'], ['group_id', 'salutation', 'firstname', 'lastname', 'street', 'zip', 'city', 'country', 'email', 'notes']],            
            ['delete', true],
        ];
    }

Below is ngRestAttributeGroups

    public function ngRestAttributeGroups()
    {
        return [
            [['street', 'zip', 'city', 'country'], 'Address', 'collapsed' => false],
        ];
    }

Update Screen
<img width="545" alt="empty_group_update" src="https://user-images.githubusercontent.com/18122838/63794742-3efb7180-c90b-11e9-9522-124c014983da.png">

Create Screen (**issue highlighted in red**)
<img width="672" alt="empty_group_create" src="https://user-images.githubusercontent.com/18122838/63794752-4458bc00-c90b-11e9-9598-3a6f76a57bbb.png">

**Comment by nadar** [comment]
yes, agree. usual create and edit are almost the same, but yes its a bug. we will fix it. thanks for the report!
