### ISSUE TITLE
When displaying the crud without group menu, and using ngRestRelations , tabs are not closed

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#360]
When displaying the crud without group menu, and using ngRestRelations to show related items.
Then when moving out of crud and returning back to the crud the related items tab still open on top on items tab

see images below

Image 1: 
Categories displayed without group menu
```php
    public function getMenu()
    {
        return (new AdminMenuBuilder($this))
	        ->node('news', 'local_library', 'newsadmin/article/index')
	            ->group('news_administrate2')
	                ->itemApi('article', 'newsadmin/article/index', 'local_library', 'api-news-article')
	        ->node('cat', 'bookmark_border', 'newsadmin/cat/index')
	            ->group('news_administrate2')
	                ->itemApi('cat', 'newsadmin/cat/index', 'bookmark_border', 'api-news-cat');
    }
```

<img width="924" alt="relationship_tabs_issue-01" src="https://user-images.githubusercontent.com/18122838/64022230-65edb980-cb3e-11e9-88d8-637d7436cf23.png">

Image 2:
Listing related articles for a category
<img width="950" alt="relationship_tabs_issue-02" src="https://user-images.githubusercontent.com/18122838/64022327-9fbec000-cb3e-11e9-9111-cd0f672d9bec.png">

Image 3 & 4:
**The problem**
<img width="956" alt="relationship_tabs_issue-03" src="https://user-images.githubusercontent.com/18122838/64022391-c54bc980-cb3e-11e9-9f59-0d7546c647d0.png">

<img width="950" alt="relationship_tabs_issue-04" src="https://user-images.githubusercontent.com/18122838/64022395-c7ae2380-cb3e-11e9-85b3-7da086b7ae3c.png">

My guess is that there is an event that is not triggered  to close the tabs when using crud without groups menu, but this event is triggered when using group menu.

Could you please direct me where to check for this issue?

**Comment by nadar** [comment]
Thanks, i will take a look at this asap.

**Comment by ifuratdev** [comment]
could you please let me know where should I look to fix this issue

**Comment by nadar** [comment]
are you using latest admin verrsion? I try to reproduce but i can not. We have a lot of ngrest relation defintions. What does the definition look like? 

You say `when using crud without groups menu` but you have a permission entry for the groups (category?)

**Comment by ifuratdev** [comment]
yes i'm using the latest version "2.1.0" for the admin

This is a fresh installation of luya 
Also this is the existing addressbook module with minor fix to show show group articles, see below fixed code, the original code is the commented out code

> 


    public function ngRestRelations()
    {
        return [
           //['label' => 'Articles', 'apiEndpoint' => Article::ngRestApiEndpoint(), 'dataProvider' => $this->getArticles()],
           ['label' => 'Articles', 'targetModel' => Article::class, 'dataProvider' => $this->getArticles()],
        ];
    }

> 

Original code (from the module) where categories displayed with group menu

> 
    public function getMenu()
    {
        return (new \luya\admin\components\AdminMenuBuilder($this))
            ->node('Addressbook', 'extension')
            ->group('Settings')
            ->itemApi('Contact', 'addressbookadmin/contact/index', 'label', 'api-addressbook-contact')
            ->itemApi('Group', 'addressbookadmin/group/index', 'label', 'api-addressbook-group');
    }
> 

Updated code for categories without group menu

> 
    public function getMenu()
    {
        return (new AdminMenuBuilder($this))
	        ->node('news', 'local_library', 'newsadmin/article/index')
	            ->group('news_administrate2')
	                ->itemApi('article', 'newsadmin/article/index', 'local_library', 'api-news-article')
	        ->node('cat', 'bookmark_border', 'newsadmin/cat/index')
	            ->group('news_administrate2')
	                ->itemApi('cat', 'newsadmin/cat/index', 'bookmark_border', 'api-news-cat');
    }
> 

let me know if you need any other info


please find below attached code for Module, Article, and Cat

[Module.zip](https://github.com/luyadev/luya-module-admin/files/3595571/Module.zip)

[Article.zip](https://github.com/luyadev/luya-module-admin/files/3595574/Article.zip)

[Cat.zip](https://github.com/luyadev/luya-module-admin/files/3595575/Cat.zip)

**Comment by ifuratdev** [comment]
note:
the only code changes from the original code is:
ngRestRelations
and
getMenu

the rest of the code is exactly the same as in the module
https://github.com/luyadev/luya-module-addressbook

**Comment by nadar** [comment]
And with the original module you don't have errors? For example the 3d param of `node()` is $template, see https://luya.io/api/luya-admin-components-AdminMenuBuilder. 

so you say you have changed only menu and ngrest relations, but why do you have complete different namespace and namings? first ist `addressbook` and second ist `newsadmin` ...

**Comment by ifuratdev** [comment]
my mistake this is the luya-module-news module not the luya-module-addressbook :)

https://github.com/luyadev/luya-module-news

i have fixed the issue you can see the issue on the demo website
https://demo.luya.io/en/admin#!/default/9/newsadmin/cat/index

in the Categories if you click on "Articles" it will show an error

The only code changes are:

ngRestRelations - to fix the issue above
getMenu to show articles/categories without groups sub-menu 

image 1:
categories without groups sub-menu 

<img width="924" alt="relationship_tabs_issue-01" src="https://user-images.githubusercontent.com/18122838/64617014-4e3bee00-d3e6-11e9-865a-4ee5ff89bab5.png">



Image 2:
original code categories with groups sub-menu 

<img width="813" alt="relationship_tabs_issue-05" src="https://user-images.githubusercontent.com/18122838/64617002-48460d00-d3e6-11e9-8c5d-8a48c671a811.png">

**Comment by nadar** [comment]
yes, but then you have modified something because the image 2 is original. i can not reproduce your problem. Image 1 looks wrong to me, there is no padding. Its not possible to set an ngrest crud menu as ROOT NODE (or at least we have never done :-D)

**Comment by ifuratdev** [comment]
That is the change that i have done to set it as a root node, below is the code to set it as a root node

And the problem only occur if you set it as root node as below

> 

    public function getMenu()
    {
        return (new AdminMenuBuilder($this))
	        ->node('news', 'local_library', 'newsadmin/article/index')
	            ->group('news_administrate2')
	                ->itemApi('article', 'newsadmin/article/index', 'local_library', 'api-news-article')
	        ->node('cat', 'bookmark_border', 'newsadmin/cat/index')
	            ->group('news_administrate2')
	                ->itemApi('cat', 'newsadmin/cat/index', 'bookmark_border', 'api-news-cat');
    }

**Comment by nadar** [comment]
yes, this wont work i assume :/ use groups and itemApi

**Comment by ifuratdev** [comment]
so no way to work :)
i was hoping it will work

**Comment by nadar** [comment]
even the design would look wrong as you can see. Maybe in future we can provide an option.
