### ISSUE TITLE
Sequential row numbering in a list view

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#380]
When working with large enough lists there is often a need for sequential numbering of the displayed data. For example, you can quickly find out the number of rows after applying filters and sorts.

This feature can be easily implemented on the client side using AngularJS

**Comment by nadar** [comment]
But if the page is paginated the next page would started from the last index, right?

yes angularjs has an `$index` variable which we could multiply with the current page. An extra attribute with the plugin `Index` might do the job very easy. Or even the angular plugin which currently exists with {{$index}}. need to test.

**Comment by nadar** [comment]
Not tested, but maybe this works :-)

```php
'myIndex' => ['angular', 'tempalte' => '$index * pager.currentPage'],
```

**Comment by Antikon** [comment]
The right variant is
`'myIndex' => ['angular', 'template' => '{{1+((pager.currentPage-1) * pager.perPage)+$index}}']`
and the myIndex property must be added to Model.

As a quick workaround it will work on a simple list. It should work on a filtered list. But it will not work when groupping the data since each group has its own index (and that is correct) which has no commons with pagination.

**Comment by nadar** [comment]
so maybe we could make a ngrest plugin `IndexNumber` (for example) which has this kind of code already inside (extend from angular plugin with predefined template). would you like to send a PR?

**Comment by Antikon** [comment]
Plugin seems to be a good idea. Unfortunately, I am not familiar with AngularJS, so it will be difficult for me.

**Comment by nadar** [comment]
i thought an ngrest plugin like (luya\admin\ngrest\plugins\Angular) should do the job, we the configuration you mentioned above. Its just the angular "plugin" with predefined template code.

**Comment by Antikon** [comment]
I mention once more that the above code WILL NOT WORK when groupping data. When the page number is more than 1 it will add 'page part' to the lists. That, of course, wrong.
![index-bug](https://user-images.githubusercontent.com/2006406/66460627-f85b7400-ea7f-11e9-8e2d-7c26bd02dd7a.png)

**Comment by nadar** [comment]
yes i understood that ;-) but we can check if grouping is active or not and therefore do not multiply with current page.
