### ISSUE TITLE
Question: String primary key 

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#385]
Hi,

I have a model with a primary key as varchar not integer, and i have function that is generating the primary key before the save (EVENT_BEFORE_INSERT)

Creating new entry is working fine, but when editing entry is it giving error (yii\base\InvalidRouteException: Unable to resolve the request:).
it seems the URLManager is not accepting Any word character (\w)

Is they any way to support this?

**Comment by nadar** [comment]
Would you please make a Pull Request? To cast the input vlaue to integer is just a security issue, but we should just check for none scalar values.
