### ISSUE TITLE
CRUD view search should not involve all the DB fields of a model

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#387]
When someone use a search filter in a CRUD list view the executed queries will be like this:
```
SELECT COUNT(*) FROM `conf_people_stored_data` WHERE (`conf_people_stored_data`.`id` LIKE '%search%') OR (`conf_people_stored_data`.`email` LIKE '%search%') OR (`conf_people_stored_data`.`unsubscribe` LIKE '%search%') OR (`conf_people_stored_data`.`surname` LIKE '%КФуsearchcc%') OR (`conf_people_stored_data`.`name` LIKE '%search%') OR ...
```

In the most cases it's not nessecary to involve all the fields, only some special fields should be touched.

I suggest to make another `ngRestScope` like 
```
public function ngRestScopes()
{
    return [
       ['list', ['surname', 'name', 'affiliation']],
       ['search', ['surname', 'affiliation']],
```

Moreover, the search filter as well as sorting mechanism uses direct SQL queries like
`SELECT * FROM `conf_people_stored_data` ORDER BY `affiliation` LIMIT 25`. When the `affiliation` model field is not a DB field, but is calculated separately, the search and the ordering fail.

**Comment by nadar** [comment]
you can override genericSearchFields to change the fields which should be looked up.

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/NgRestModel.php#L445-L455

**Comment by nadar** [comment]
Can we close this?

**Comment by nadar** [comment]
If there is any further issue, reopen.
