### ISSUE TITLE
Fatal error for selectModel plugin being used in data pool

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-admin#389]
### What steps will reproduce the problem?
A model with selectModel plugin being used with data pools.
It triggers error:
```
[0h1db2o83ip2ui0112ja519rqd][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The requested pool identifier 'posted' does not exist in the ngRestPools() definition. in /var/www/luya-kickstarter/vendor/luyadev/luya-module-admin/src/ngrest/base/NgRestActiveQuery.php:116
Stack trace:
#0 /var/www/luya-kickstarter/vendor/luyadev/luya-module-admin/src/ngrest/plugins/SelectModel.php(215): luya\admin\ngrest\base\NgRestActiveQuery->inPool('posted')
#1 /var/www/luya-kickstarter/vendor/luyadev/luya-module-admin/src/ngrest/plugins/Select.php(87): luya\admin\ngrest\plugins\SelectModel->getData()
#2 /var/www/luya-kickstarter/vendor/luyadev/luya-module-admin/src/ngrest/base/Plugin.php(769): luya\admin\ngrest\plugins\Select->serviceData(Object(yii\base\Event))
```
### Additional infos
As I understood the error because pool's identifier from main model being passed in request params and SelectModel->getData() uses pool's identifier from main model for relation model here:
```
luya-kickstarter/vendor/luyadev/luya-module-admin/src/ngrest/plugins/SelectModel.php

209     public function getData()
210     {
211         $data = [];
212
213         $class = $this->modelClass;
214
215         $query = $class::ngRestFind()->inPool(Yii::$app->request->get('pool'));
```
but relation model doesn't have same data pools as main model (obviously) so the error.

**Comment by nadar** [comment]
Hey @jettero777 could you please post the pool config code from the models? The pool ID will be passed to children, but should not throw an exception.

**Comment by jettero777** [comment]
> 
> 
> Hey @jettero777 could you please post the pool config code from the models? The pool ID will be passed to children, but should not throw an exception.

Hi @nadar 
config for main model
```
    public function ngRestAttributeTypes()
    {
        return [
            'account_id' => [
                'selectModel',
                'modelClass' => Account::class,
                'valueField' => 'id',
                'labelField' => 'username',
            ],
        ];
    }

    public function ngRestPools()
    {
        return [
            'pending' => ['posted' => '0'],
            'posted' => ['posted' => '1'],
        ];
    }
```
pool config for relation model Account
```
    public function ngRestPools()
    {
        return [
            'general' => ['type' => 'general'],
            'publishing' => ['type' => 'publishing'],
        ];
    }
```

**Comment by nadar** [comment]
Now i see the problem as well:

1. opening the first model with`posted` pool.
2. `posted` pool will provide its pool identifier to the account model which has an ngrest pool `type`.
3. As the passed pool *has pools* it will throw the exception: https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/NgRestActiveQuery.php#L115

I think we can just remove this exception. If the pool identifier is not in the list of identifiers, just skip instead of throw an exception.

Thanks for the report, i will fix it quickly.
