### ISSUE TITLE
adminqueue being run by backend though fake cronjob in bootstrap is switched off

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-admin#394]
I need a queue for some custom jobs so I try to use luya's builtin \Yii::$app->adminqueue for own jobs. In order to not create another similar queue and log.

But though I don't use fake cronjob ($autoBootstrapQueue = false) the queue jobs are triggered anyway when I use admin backend, because there is call Yii::$app->adminqueue->run(false) in TimestampController.
And if jobs are heavy (several minutes to complete) it gets impossible to work in admin, because it freezes until job is complete.

So if it is intended behavior I think better to document somewhere that adminqueue should be used only for small lightweight jobs.

**Comment by nadar** [comment]
hey @jettero777 so maybe we should not run the que if autoBootstrapQueue is disabled. This would fix your problem and would be more straight. What do you think?

**Comment by jettero777** [comment]
> 
> 
> hey @jettero777 so maybe we should not run the que if autoBootstrapQueue is disabled. This would fix your problem and would be more straight. What do you think?

Hi @nadar yep, it should resolve it.
And if autoBootstrapQueue is enabled it will run in bootstrap anyway as I understand, so this can be left as only place to run it (and CLI of course).

**Comment by nadar** [comment]
would you like to send a PR?

**Comment by jettero777** [comment]
Yes, I will send soon.
