### ISSUE TITLE
Block Management is_disabled functionality

### ISSUE THREAD

**Issue by buttflattery** [luyadev/luya-module-admin#4]
- OS Information: Windows 10 Pro
- System Type: 64-bit OS x64-based Processor
- Browser Info: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Browser Info : Firefox 57.0 (64-bit)

Under `Block Management` section if I click on the `x` icon against the `News: Latest Headlines` row under the `is Disabled` section it reloads the page and logs me out and displays the login page, and after I log in and go back to the same section there is still `x` icon displayed under `is Disabled` column and is that some kind of feature restricted in the demo version, either case it should not log me out and take me to the login page without displaying any success or error messages.

![image](https://user-images.githubusercontent.com/1536454/33960940-1fcc15ee-e06e-11e7-8b19-b07814e20c48.png)

**Comment by nadar** [comment]
@buttflattery Yes, this is only a restriction in the demo, the demo user is not allowed to make put requests on the API. We could hide this section in the luya demo.
