### ISSUE TITLE
problem with Datepicker

### ISSUE THREAD

**Issue by mrtrinhvn** [luyadev/luya-module-admin#408]
### What steps will reproduce the problem?
In the model: 
public function ngRestAttributeTypes()
    {
        return [  
            'created_timestamp' => ['class' => Date::class, 'emptyMessage' => '-', 'format' => 'dd/MM/yyyy'],
        ];
    }
There is no option for innit the default value
The format always is dd.MM.yyyy
datepicker twoo small on mobile device for selecting date
### What is the expected result?
There is an option for innit the default value, eg current date
format' => 'dd/MM/yyyy' take effection
On mobile device, the datepicker display enough clear to be selected

### What do you get instead? (A Screenshot can help us a lot!)

![z1634844832411_1fca7cf9799f2b35cae307e99d55c359](https://user-images.githubusercontent.com/3391289/69623384-60d4d380-1075-11ea-8ecc-18ed2615ac56.jpg)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by mrtrinhvn** [comment]
2 things:
Formarting not work
No where to set a date

**Comment by nadar** [comment]
To format, try: https://docs.angularjs.org/api/ng/filter/date - this is what formats the date in the frontend, it will always send a unix timestamp.

So the problem is that the datepicker locks not good on mobile device?

**Comment by TheMaaarc** [comment]
Datepicker doesn't look great on mobile, that's true.  
We currently use https://github.com/720kb/angular-datepicker (their live demo doesn't look great on mobile either) – maybe we can improve the current picker or we need to switch to a different library.
