### ISSUE TITLE
Outdated echarts.js 

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-admin#428]
Seems that echarts.js shipped with the package is outdated.
I try to use charts with datasets and it is not working though it works on current echarts lib. Datasets were implemented there since 4.0 version.

In composer.json version of echarts is "bower-asset/echarts": "~3.8.5", which is 2 years old yet.
I tried to update it via composer but looks like the lib is precompiled into js resources.

**Comment by nadar** [comment]
So then we might update the dependency, are there any major breaks we can expect from 3 to 4?

**Comment by jettero777** [comment]
Here is changelog https://www.echartsjs.com/en/changelog.html#v4-0-0

Pie chart in User History uses very basic features and should work on latest echarts version too.
There are changes in label options, but old formatting should work too:

> [+] Since ECharts4, the options label and itemStyle has been flattened. The original level of normal is not needed any more, which make ECharts option more neat. As always, The previous option style in ECharts3 is still be compatible.
