### ISSUE TITLE
'Required' rule for i18n field

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#438]
Let's assume we have an `title` i18n field and 3 languages EN DE FR. We want that title must be set for EN and DE languages and optionally for French. If we set a required rule for `title`, the rule will be satisfied when title in any language is present (in a admin CRUD).

In regard of this and 3.0 version, I still suggest thinking about extending the `i18n `property of the ngRest model.
Like 
```
$i18n = [
    'title' => [
        'en' => ['reqiuired', 'default'],
        'de' => 'required',
        'fr'
    ]
];
```

Moreover, when we want both the EN and DE languages to be mandatory, it would be nice if the fields for `title` for these languages are shown in a CRUD by default.

#330 #383

**Comment by nadar** [comment]
Yes i agree on this

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/blob/master/src/validators/I18nRequiredValidator.php
