### ISSUE TITLE
SelectArray and broken relation

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#439]
I suggest thinking about the fact that `SelectArray` plugin spoils the model data. The plugin itself is intuitive and that's good. 
But every time I'm using it, the Yii 2 relations stop working. Of course, this "feature" is documented and a workaround provided, but this is a really bad way IMHO. This behavior is contrary to the ActiveRecord - one of the main features of Yii 2.

**Comment by nadar** [comment]
You mean `SelectModel` i assume? and your talking about the fact that its override the model attribute value? Or what doe mean exactly

**Comment by Antikon** [comment]
I mean exactly the `SelectArray` plugin. But you made me doubt. I'll check once more.

**Comment by nadar** [comment]
Anyhow, i am not sure what behavior you are talking about, the assigne of the value which is then different to the active record value i assume?

**Comment by nadar** [comment]
@Antikon please check https://github.com/luyadev/luya-module-admin/pull/444 - this might this issue very easy, you just have to turn of the behavior.
