### ISSUE TITLE
No vertical scrollbar in Chrome

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#440]
### What steps will reproduce the problem?
Open an admin panel in Chrome. Make the window height is small enough.

### What is the expected result?
Vertical scrollbars should appears.

### What do you get instead? (A Screenshot can help us a lot!)
No scrollbars in Chrome (Windows). Everything is fine in Firefox.

![scrollbars](https://user-images.githubusercontent.com/2006406/72445812-61f7c680-37c3-11ea-93d3-f0ca8b22cab9.png)

**Comment by nadar** [comment]
As far as i can say, its an expected behavior to not display the toolbars, but not sure. Maybe @TheMaaarc knows something about.

**Comment by TheMaaarc** [comment]
The scrollbars should be hidden, that's true. Seems that Firefox doesn't like that.

The issue is that the scrollbars do need quite a bit of space on Windows – but maybe it's bad practice to hide them. If it's a big issue we can re-evaluate that decision.

**Comment by Antikon** [comment]
I am pretty sure that hiding the default UI element is not good. The admin area could be used by not only the experienced developers but also by ordinary users (for example, when working in some custom module). In this case, how can they guess that the central (second) column in the admin panel contains more settings than can be seen?

**Comment by nadar** [comment]
as far as i can remember on apple devices you won't have scrollbars as well, people know intuitively where to scroll and where not. Even for example slack for linux hides the scrollbar, its maybe also a relic of the past, cause people don't have to click on the scrollbar - they just scroll with touch gestures or mouse wheel :-) but thats my opinion.

**Comment by Antikon** [comment]
Why not leave the default browser behavior? Let Windows users have the opportunity to enjoy their usual scrollbars.

PS. I don't have any Apple device. But don't they show any scrollbars even on scroll? How will user know the document length?

**Comment by TheMaaarc** [comment]
Can't argue with that.

**Comment by TheMaaarc** [comment]
@Antikon Feel free to test it on the master branch.

**Comment by nadar** [comment]
👍
