### ISSUE TITLE
view in $authOptional on \luya\admin\ngrest\base\Api

### ISSUE THREAD

**Issue by vavepl** [luyadev/luya-module-admin#448]
When i added 'view' to $authOptional on Controller i got error "Trying to get property 'is_api_user' of non-object"
![image](https://user-images.githubusercontent.com/7990096/73595497-b320ed80-4519-11ea-820d-c148c4502632.png)

I think 
[Here](https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/Api.php#L463) and [Here](https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/base/actions/ViewAction.php#L66) needed to check if is $identity

**Comment by vavepl** [comment]
maybe in AdminUser add only isApiUser and there to check identity & is_api_user?

**Comment by nadar** [comment]
Yes, maybe we could just check whether adminuser isGuest or not. like

if (Yii::$app->adminuser->isGuest && .....

would you like to send a PR?

**Comment by vavepl** [comment]
okey
