### ISSUE TITLE
Can't login to admin panel!

### ISSUE THREAD

**Issue by MohammadShafiee** [luyadev/luya-module-admin#45]
Hello,
I installed luya but I can't login to admin panel. When I open the url: http://localhost/cms/luya/public_html/admin the page redirected to http://localhost/cms/luya/public_html/admin/login, then I enter username/password and push login button. A request made to url: http://localhost/cms/luya/public_html/admin/login/async that its response is JSON: {"refresh":true,"errors":false,"enterSecureToken":false}
The page refreshed and again login page appeared!!!

**Comment by nadar** [comment]
Hi @MohammadShafiee, sound strange. Can you store data in the session?

**Comment by MohammadShafiee** [comment]
Hi dear @nadar 
I think you're right. I transfer sessions into the database (\yii\web\DbSession) and the problem solved. But I don't know exactly what was the reason?!
Thank you.

**Comment by nadar** [comment]
So we can close this issue? I think this is some problem with your webserver. (so its not a luya related problem)

**Comment by MohammadShafiee** [comment]
Yes.
Thank you.

**Comment by makroxyz** [comment]
Please help!
It happens to me too even with yii\web\DbSession!!
I can't login to dashboard

I'm on luya 1.0.5, php7.0.
It happens suddendly!

**Comment by nadar** [comment]
@makroxyz try to disabled yii developer toolbar, do you have a frontend user login?

**Comment by makroxyz** [comment]
developer toolbar is disabled, I have a module with frontend login

**Comment by makroxyz** [comment]
Same issue. Sometimes it redirects me after login to login again, sometimes it shows me dashboard but redirects me to logout when I click on pages or files...

what redirects me is in main.js script row 9702
```js
if (data.status == 401 || data.status == 403 || data.status == 405) {
                	if (!data.config.hasOwnProperty('authToken')) {
                		window.location = "admin/default/logout";
                	}
                } else if (data.status != 422) {
                	var message = data.data.hasOwnProperty('message');
                	if (message) {
                		AdminToastService.error(data.data.message, 10000);
                	} else {
                		AdminToastService.error("Response Error: " + data.status + " " + data.statusText, 10000);
                	}
                    
                }
```

**Comment by nadar** [comment]
have you enabled file cache?

**Comment by nadar** [comment]
please provide composer.json

**Comment by makroxyz** [comment]
no file cache
here's my composer.json

```json
{
    "name": "luyadev/luya-kickstarter",
    "description": "The kickstarter project for a new LUYA application.",
    "type": "project",
    "license":"MIT",
    "require": {
        "luyadev/luya-core" : "~1.0.0",
        "luyadev/luya-module-admin" : "~1.0.0",
        "luyadev/luya-module-cms" : "~1.0.0",
        "luyadev/luya-bootstrap3" : "~1.0.0",
        "luyadev/luya-generic" : "~1.0.0",
        "bower-asset/animate.css": "*",
        "rmrevin/yii2-fontawesome": "~2.17",
        "bupy7/yii2-flexslider": "dev-custom",
        "ruskid/yii2-csv-importer": "*",
        "toriphes/yii2-console-runner": "*",
        "omnilight/yii2-scheduling": "*",
        "loveorigami/yii2-magnific-popup": "*",
        "hal/yii2-jasperbridge": "*",
        "yii2tech/file-storage": "*",
        "ayrozjlc/yii2-blockui": "*",
        "luyadev/luya-module-news": "~1.0.0",
        "2amigos/yii2-usuario": "~1.1.4",
        "kartik-v/yii2-widget-select2": "~2.1.0",
        "kartik-v/yii2-widget-touchspin": "*",
        "kartik-v/yii2-grid": "@dev",
        "kartik-v/yii2-widget-growl": "*",
        "kartik-v/yii2-dialog": "*",
        "luyadev/luya-module-basicauth": "~1.0.0"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/makroxyz/yii2-flexslider.git"
        },
        {
            "type": "composer",
            "url": "http://packages.halservice.eu/yii2"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require-dev": {
        "yiisoft/yii2-gii" : "~2.0.0",
        "yiisoft/yii2-debug" : "~2.0.0",
        "luyadev/luya-testsuite" : "~1.0.0"
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "public_html/assets": "0777",
                    "public_html/storage": "0777",
                    "runtime" : "0777"
                }
            ]
		},
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        },
        "asset-pattern-skip-version": "(-build|-patch)",
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        }
    },
    "config": {
        "secure-http": false,
        "fxp-asset" : {
            "pattern-skip-version": "(-build|-patch)",
             "installer-paths": {
                "bower-asset-library": "vendor/bower"
            }
        }   
    }
}

```

**Comment by nadar** [comment]
could you try use the luya admin ~1.1.0 constraint and run composer update?

**Comment by nadar** [comment]
(btw: run migrate and import afterwards!)

**Comment by makroxyz** [comment]
OMG.... updated...  
./luya migrate --> nothing to migrate
./luya import --> seems OK

when I try to login... DB exception (is_api_user missing on admin_user table) so I added manually...
after login... a lot of UnknownPropertyException (api_last_activity) and shows white dashboard

**Comment by makroxyz** [comment]
I added api_last_activity column to admin_user...
No more errors but same as before.... it fires me to logout as I click on Pages

**Comment by nadar** [comment]
Please contact me in gitter (https://gitter.im/luyadev/luya) or slack (https://slack.luya.io). 

Regarding migration: 

+ Have you ever used the dev-master of luya admin? 
+ The logout can appear when you are logged in as frontend user.
+ The yii2 debug panels introduced something which force user logout, so ensure again yii2 debug is disable in your config bootstrap and module section.
