### ISSUE TITLE
Emulate behavior of <a> tag in menu (or put real <a> there)

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#451]
Now menu items in admin area is made of spans 
`<span class="modulenav-link modulenav-link-active" ng-click="click(sub)"...`
It looks like link but it doesn't implement behavior of <a> tag. For example, you cannot do the right click and copy link, open link in new window etc. The last one is really useful because sometimes one needs to work with multiple pages in admin area at the same time. 

For example, on one page I have a table with information about people (gender, age, degree, etc.). And on the other page there is a form with a list of rooms in the hotel (with a visual relation between them, for example). I need to settle people in rooms. 
The usual workflow happens like this: I choose a room, check its type, check those who live in the next room and so on. After that I look at a table with people and search for a suitable pair. And the I go back to the rooms and settle those 2 (or more people).

Can those <span> be replaced by <a> tags?

**Comment by nadar** [comment]
I understand that. `you cannot do the right click ` but a right click on `ng-click=click()` would not work anyhow i assume. You can test and send a PR, maybe @TheMaaarc could assist with css. 

But if you use a you need to take ui-sref otherwise a tags won't work.
