### ISSUE TITLE
Some mess with vendor.js

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-admin#452]
Hello, please check changes for [src/resources/dist/vendor.js](../blob/master/src/resources/dist/vendor.js)
Commits fe5b3f07bde5b4eadf9a400b53ca27b7b6de1a68 520bc4c8e241828c477684cd72b6d201a2e63f7f c3c62d26a03c43f7dc7e405e8658b8dd501980ae c5f90942e28ace9d4749fe1a3815ca208ea48177
are turning support for ECharts4 on, off, on and again off :)

**Comment by nadar** [comment]
Thanks, will do some tests. :+1:

**Comment by nadar** [comment]
Hey @jettero777 this happens if someone compiles the js/css without updating its vendor folder (run `composer install`) - we might automat this task. But we always run those tasks before a new release. Thanks for making us aware of this!
