### ISSUE TITLE
Collapsable menu not changing title when returning to dashboard

### ISSUE THREAD

**Issue by EdoMon93** [luyadev/luya-module-admin#453]
### What steps will reproduce the problem?

On mobile:
1. Login into admin
2. Go to any module
3. Go back to dashboard
4. The title on the collapsable menu will show the title of last visited module.

### What is the expected result?

The title should be empty or "dashboard".

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/32374370/74383298-8c35a780-4db4-11ea-9b38-158ed53c37f2.png)

![image](https://user-images.githubusercontent.com/32374370/74383352-a7a0b280-4db4-11ea-835c-6802e05ac789.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] ''
3: [ini_get('error_reporting')] '32767'
4: [phpversion()] '7.2.18'
5: [php_ini_loaded_file()] 'C:\\wamp64\\bin\\apache\\apache2.4.39\\bin\\php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.2.18'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.25
| PHP Version      | 7.2
| Platform         | Apache
| Operating system | tested on Win10 and Ubuntu 18.04

**Comment by nadar** [comment]
Thanks for the report. Yes, it looks like a bug, i will do some research.
