### ISSUE TITLE
Title of the first pool is being displayed for all other pools of the model

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-admin#455]
### What steps will reproduce the problem?
several ngRestPools in some model

### What is the expected result?
title above list/single views should be same as currently selected pool

### What do you get instead? (A Screenshot can help us a lot!)
title from first pool (first in menu) is being shown for all other pools too

![Untitled-1](https://user-images.githubusercontent.com/12475667/74552980-6a305680-4f67-11ea-8eda-306a4c1c9dd3.png)

**Comment by nadar** [comment]
Thanks, i need to take a closer look on this. But yes i can confirm this bug!

**Comment by nadar** [comment]
And thanks for the report @jettero777! its very important for us.

**Comment by hbugdoll** [comment]
This bug is related to all admin menu items with same `apiEndpoint`, it's not restricted to NgRestPools.

e.g. title is "Foo" for all three following menu items:
```
return (new AdminMenuBuilder($this))
   ->node('My Module', '...')
   ->group('Group1')
      ->itemApi('Foo', '...', '...', 'api-mymodule-foo')
      ->itemPoolApi('Foo Pool1', '...', '...', 'api-mymodule-foo')
   ->group('Group2')
      ->itemPoolApi('Foo Pool2', '...', '...', 'api-mymodule-foo');
```

**Comment by hbugdoll** [comment]
Second parameter in `getApiDetail(apiEndpoint, pool)` retrieving CRUD title in
https://github.com/luyadev/luya-module-admin/blob/b9f53ac22f4a6137e6d9ce4701ef82be578b2144/src/ngrest/render/RenderCrud.php#L120 was missing.
