### ISSUE TITLE
Update Bootstrap to v4.3.1

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-admin#46]
Update Bootstrap to [v4.0.0](https://github.com/twbs/bootstrap/releases/tag/v4.0.0).

- [x] Update code
- [x] Check all elements
- [x] Update [luya-module-cms](https://github.com/luyadev/luya-module-cms)
- [x] [Don't Worry Be Happy](https://www.youtube.com/watch?v=d-diB65scQU)  🎉

**Comment by nadar** [comment]
@TheMaaarc latest version is already 4.1 please udpate to latest version.

**Comment by nadar** [comment]
+ Tables in Detail Views
+ Checkboxes in File Manager
![image](https://user-images.githubusercontent.com/3417221/57210301-7355c580-6fdc-11e9-90cb-084c2d78a9ff.png)
+ New icon in file manager for details? (@rolandschaub)

**Comment by TheMaaarc** [comment]
I'll close the issue until we find the next problem.
