### ISSUE TITLE
UI admin display issue

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya-module-admin#461]
### What steps will reproduce the problem?
When a page contains several blocks, the left menu scroll with the page. It should remain fixed as the right menu.

### What do you get instead? (A Screenshot can help us a lot!)
![Screenshot 2020-02-23 at 11 11 01](https://user-images.githubusercontent.com/3844254/75110352-784c3a00-562d-11ea-993d-ca14ddd46cb8.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 3.0.0.0 (Admin Module)
| PHP Version      | 7.3.11
| Platform         | AMPPS.
| Operating system | OSX

**Comment by nadar** [comment]
@TheMaaarc Maybe this is related to https://github.com/luyadev/luya-module-cms/issues/239 and the removal of padding:0px (which has been done while revert the hide scrollbar change)?

**Comment by TheMaaarc** [comment]
It was a safari specific issue (we used the overflow shorthand form `overflow: hidden auto;` but safari doesn't support that).

Fixed on the master branch of the cms module (https://github.com/luyadev/luya-module-cms/commit/b5f9b553006c2ab8f2d7a8398268b47358c400a9).

**Comment by JDL747** [comment]
The issue is resolve in the CMS admin section but in the admin.

<img width="1440" alt="Screenshot 2020-02-24 at 11 31 46" src="https://user-images.githubusercontent.com/3844254/75145546-6b951800-56f9-11ea-811a-06a794e6c2e7.png">
