### ISSUE TITLE
StorageFilter::applyFilterChain() not optimal

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-admin#467]
If I get it right from the code, when we call StorageFilter::applyFilterChain() it is applying effects one by one, saving intermediate image to filesystem and reading images back after each step.

For now it is not a big issue because built-in filter chains consist from one effect, but if you create custom chain with many effects (scaling, cropping, watermarks, etc) then saving/reading intermediate images will affect quality because saving is lossy.

Also it affects performance as we use multiple slow filesystem operations.
Intermediate image can be stored in memory (in var) instead and being saved one time after all processing is done.

**Comment by nadar** [comment]
Hey @jettero777 - what you are saying is true, it would be nice to see a PR, i would love to improve that as well, its very memory consuming. Maybe i can assist on a solution? Concrete implementation suggestions?

**Comment by jettero777** [comment]
Hey @nadar 
Unfortunately for the moment too little time to make a PR (deadlines :), maybe later.
Regarding possible implementations, for example crop effect, now it works like this
```
// read and crop
$image = Image::crop($loadFromPath, $this->effectChainValue($imagineEffectName, 'width'), $this->effectChainValue($imagineEffectName, 'height'));

// then save
Image::autoRotate($image)->save($imageSavePath, $this->effectChainValue($imagineEffectName, 'saveOptions'));
```
And next effect in chain again loads from and save to file.

It can be change to this
```
// load resource before processing chain
$image = \yii\imagine\Image\Image::getImagine()->open($loadFromPath);

// start chain, do crop for example
$image = Image::crop($image, $this->effectChainValue($imagineEffectName, 'width'), $this->effectChainValue($imagineEffectName, 'height'));

// do all other chain effects to $image resource
...

// and save to file only at the end
$image->save($imageSavePath);

// imagine does ->clear() and ->destroy() on destruct that should free memory
unset($image);
```

**Comment by nadar** [comment]
Thanks for the details, i will take care of this. Do you have an assumption of how much memory we could save by changing this?

**Comment by nadar** [comment]
@jettero777 please take a look at: https://github.com/luyadev/luya-module-admin/pull/484
