### ISSUE TITLE
Storage page is very slow

### ISSUE THREAD

**Issue by mhunesi** [luyadev/luya-module-admin#470]
### What steps will reproduce the problem?

Hi,
I have 576 folders in storage and Storage page is very slow.
You see this video. https://www.mustafaunesi.com.tr/uploads/a/screen.mov

### What do you get instead? (A Screenshot can help us a lot!)
![image](https://user-images.githubusercontent.com/15876915/76733850-af1bf880-6772-11ea-84f1-f065b024207b.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by mhunesi** [comment]
This error continues. You can use ng-if instead of ng-show. 

<ul class="folders" ng-if="folder.subfolder === true && folder.toggle_open==1">

/vendor/luyadev/luya-module-admin/src/views/layouts/_angulardirectives.php:215

**Comment by nadar** [comment]
:+1: i will check that

**Comment by nadar** [comment]
@mhunesi its already ng-if, see:

https://github.com/luyadev/luya-module-admin/blob/master/src/views/layouts/_angulardirectives.php#L215

**Comment by mhunesi** [comment]
Yes. I have old version. Thanks for time.
