### ISSUE TITLE
Exception Handling: Delete warning popup window

### ISSUE THREAD

**Issue by siripravi** [luyadev/luya-module-admin#488]
### What steps will reproduce the problem?
When I try to delete a record from ngRestModel, I get this popup

### What is the expected result?
From where this window comes up? How to configure its contents(like message and behavior etc.)
Another issue:
How to hide delete button for specific rows conditionally. If a record has already been deleted(is_deleted = true), we should not allow the user to delete it again.
![delete popup](https://user-images.githubusercontent.com/174201/81368423-597a2180-910d-11ea-9658-cc0c67dd0d52.PNG)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
> From where this window comes up?

Its the default behavior for the delete button. If your language is missing, you are welcome to help us translate those messages :-) let me know if you need further assistence on this.

> How to hide delete button for specific rows conditionally.

There was already an issue regarding this (https://github.com/luyadev/luya-module-admin/issues/16) Its not possible yet, but it might be interessting indeed!

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/issues/16 has been implemented

**Comment by siripravi** [comment]
Thank you. I will check.
