### ISSUE TITLE
<luyaElement> analogue for <zaaElement>

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#493]
Each AngularJs `<zaaElement>` directive contains a two-column layout and label in its template. In most cases to be able to reuse these directives, you must have "simpler" versions of these directive. 

An example already exists. There are `<zaaSelect>` and `<luyaSelect>` directives.

I suggest making the same simplified versions of the remaining existing directives.

**Comment by nadar** [comment]
Yes thats a great idea, but it will take time to do :-) if you like, yes please send a PR.

**Comment by Antikon** [comment]
Ок, I'll do it!
