### ISSUE TITLE
Color the CRUD table in funny colors and add tooltips

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#494]
When working with numerous data in a table, it is often convenient to use several information layers.

One of the layers can be coloring both the text itself and the table cells in the colors corresponding to the data.

A second option would be to add a tooltip when hovering over a cell.

I suggest to discuss the possibility of such enhancements.

**Comment by nadar** [comment]
Yes i do agree but maybe https://luya.io/api/luya-admin-ngrest-plugins-Badge might help?

**Comment by Antikon** [comment]
Glad you agree with me.

Here is some real world examples.

I have users, and a small part of users have a comment describing their "features". There is no need to give a separate column for comments, since the number of users with comments is about 5%. I want to add a tooltip to the name of these special users.

The same thing can be said about cell coloring. I want to be able to color individual cells (for example, those in which the values go beyond a certain range).

The main question is how to pass conditions in `ngRestAttributeTypes()` for certain attributes.
