### ISSUE TITLE
Default color for <a> tags in CRUD table

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#496]
Currently links in admin area are underlined only when you hover over them. Otherwise, they are no different from ordinary text.

I suggest to add color to them. Some kind of `#062775` seems to be good.

**Comment by nadar** [comment]
Maybe we should add an underline. But could you show me an example? In which container are you using the link? We should not set this global, but we can for certain containers.

**Comment by Antikon** [comment]
Even underline will be better than nothing.

I just use `html` type for one attribute. And generate html like this
'<a href="path/to/file.pdf">Abstact title</a>'

Here are the examples of different variants.

**No emphasizing.**
![links](https://user-images.githubusercontent.com/2006406/82052339-2400a580-96c4-11ea-8230-2579e6802100.png)

**Underline**
![links_underline](https://user-images.githubusercontent.com/2006406/82052335-22cf7880-96c4-11ea-8e7c-eea2663eea6d.png)

**Color**
![links_color](https://user-images.githubusercontent.com/2006406/82052341-2400a580-96c4-11ea-8017-012a69632376.png)

In principle, underlining is enough.

**Comment by nadar** [comment]
@TheMaaarc should not be a big deal, what do you think?
