### ISSUE TITLE
gif file upload error

### ISSUE THREAD

**Issue by flashjay** [luyadev/luya-module-admin#505]
### What steps will reproduce the problem?

when upload a gif file to admin/storage, sometimes it will got 502 error; then click that folder which the gif put on can alse raise error.

GIF file source: https://ddyyxc-1254110062.cos.ap-guangzhou.myqcloud.com/book/upload/cowork/4/20200306232336-59c76fc4bc89caf6f28b97e9e2296e10.gif

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
increase the memory of your webserver

**Comment by nadar** [comment]
check the log files for more informations otherwise i am unable to help here

**Comment by flashjay** [comment]
it's crash on calling Imagick::coalesceImages when create thumbnail ( on my mac, centos works fine). so maybe imageick lib have some bug.

**Comment by nadar** [comment]
all right 👍, maybe also try the luya kickstarter docker image, whether it works with this config or not
