### ISSUE TITLE
Recursive loop in list view when using selectModel

### ISSUE THREAD

**Issue by martinpetrasch** [luyadev/luya-module-admin#51]
### What steps will reproduce the problem?

Make two models. Both are using a **selectModel** in their ngRestConfig (ngRestAttributeTypes) and they should reference each other. 

### What is the expected result?

You want to be able to select and reference the other model by id.

### What do you get instead?

If you are in **list view**, you'll get a recursive loop exceeding memory limit or execution time. Update and create views are working without problems.

**Comment by nadar** [comment]
Try to use SelectRelationActiveQuery instead.

**Comment by martinpetrasch** [comment]
Thanks for the work around. It's working!

**Comment by nadar** [comment]
Not sure if this is a workaround or a problem we can not fix.

**Comment by nadar** [comment]
Going to close this, as its not possible with this method to prevent this problem.
