### ISSUE TITLE
Increase the size of the field for the queue

### ISSUE THREAD

**Issue by dven84** [luyadev/luya-module-admin#516]
Hello!
Is it possible to increase the field "job" to "mediumblob"?
We also use this queue to send emails.

**Comment by nadar** [comment]
Hi @dven84 

Which table? Could you explain please a little bit more? Thanks

**Comment by dven84** [comment]
table `admin_queue`

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/blob/master/src/migrations/m181023_135132_scheduler.php#L18

This is from https://github.com/yiisoft/yii2-queue

Could you make an example what job looks like in your case?

**Comment by dven84** [comment]
After checkout the order (our custom module), the email template is filled in and sent to the queue as a job. But the size of the email does not fit the current size of the "job" field.

**Comment by dven84** [comment]
I will just solve it with my migration. thank you
