### ISSUE TITLE
Checking class existance in getDiffCount() method

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#520]
Install some module via composer.json (news, for example). Apply migration and so on...
Log in to admin area. Everything is ok.

Then remove module from composer (and from config, of course).

Log in to admin area. An error message "Class 'luya\news\models\Cat' not found" will appears.

This error comes from `getDiffCount()` method of `UserAuthNotification` class. This method does not check the existance of class, which name comes from `admin_user_auth_notification` table.

I think the class existence should be checked, and may be some table cleanup should be performed (in case of obsolete data).

**Comment by nadar** [comment]
Thanks for the report, indeed we should check with `class_exists` function whether a class exists or not. Would you like to send a PR?

**Comment by Antikon** [comment]
I'm sorry, I'm too busy lately. But I didn’t forget about the promise to make AngularJs directives.

**Comment by nadar** [comment]
👍 ok i will fix it. thanks for the report
