### ISSUE TITLE
Password change not possible: New password fields not showing up

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-module-admin#535]
### What steps will reproduce the problem?
Try to change the password from admin.

### What is the expected result?
Possible to change the password.

### What do you get instead?
[See here](https://i.imgur.com/B4HVDOT.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.6.0
| LUYA Admin | 3.4.0
| PHP Version      | 7.4
| Platform         | Apache
| Operating system | Linux Server

**Comment by nadar** [comment]
We do have several such "none appearing" bugs it seems. Either it's due to angularjs latest patch or browser updates. I already fixed a few of them. thanks for the report.

**Comment by nadar** [comment]
<img width="963" alt="Bildschirmfoto 2020-07-25 um 13 06 26" src="https://user-images.githubusercontent.com/3417221/88455690-b3ba9100-ce77-11ea-8df9-039af51a7843.png">

seems to work on my device. latest dev-master of cms and admin

**Comment by JohnnyMcWeed** [comment]
Nothing here... [This is the html output](https://i.imgur.com/OIzcl5c.png)

**Comment by nadar** [comment]
strange, can you see the password field in the demo application? https://demo.luya.io/

**Comment by JohnnyMcWeed** [comment]
@nadar yes I can see it...

**Comment by nadar** [comment]
The demo contains cms version 3.3.0.0 and admin version 3.3.1.0

i was trying local with cms und admin latest dev-master and the password field is visible.

can you try dev-master constraints just to be sure

**Comment by nadar** [comment]
cms diff: https://github.com/luyadev/luya-module-cms/compare/3.3.0...master

admin diff: https://github.com/luyadev/luya-module-admin/compare/3.3.1...master

**Comment by JohnnyMcWeed** [comment]
Composter.lock shows this....
[Admin](https://i.imgur.com/YdXEsK7.png)
[CMS](https://i.imgur.com/JfazOHM.png)

Isn't it correct?

**Comment by nadar** [comment]
Is there someone else who can reproduce this error on latest dev-master for cms and admin? @boehsermoe @TheMaaarc @rochdi80tn 

@JohnnyMcWeed exact browser version?
