### ISSUE TITLE
Bug related to SoftDelete

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#546]
I am not sure yet, just saw the error, have to research. maybe related to #542 

![image](https://user-images.githubusercontent.com/3417221/89270408-96d24a80-d63b-11ea-8e68-c2b48be036a1.png)

## Update with potential Fix

In order to fix querys with SoftDeleteTrait like this:

```php
UserOnline::find()
->select(['lock_pk', 'lock_table', 'last_timestamp', 'u.firstname', 'u.lastname', 'u.id'])
->where(['!=', 'u.id', $userId])
->joinWith('user as u')
->asArray()
->all()
```

use instead the full table name in the field selection (and where condition)

```php
UserOnline::find()
->select(['lock_pk', 'lock_table', 'last_timestamp', 'firstname', 'lastname', 'admin_user.id'])
->where(['!=', 'admin_user.id', $userId])
->joinWith('user')
->asArray()
->all()
```

**Comment by nadar** [comment]
@boehsermoe if the table name is aliased your proposed solution won't work, maybe we should use `$query["{{%$field}}"] = (is_array($value)) ? $value[1] : !$value;` instead.

**Comment by boehsermoe** [comment]
Looks like a bigger problem 😕 https://github.com/yiisoft/active-record/issues/33
