### ISSUE TITLE
SVG upload problem

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#6]
Problem with uploading SVG files.

**Comment by TheMaaarc** [comment]
![image](https://user-images.githubusercontent.com/3450438/34095681-a705ec58-e3d2-11e7-9792-63bb71d30bee.png)

**Comment by TheMaaarc** [comment]
The mime type should be "image/svg+xml".

**Comment by TheMaaarc** [comment]
Example SVG files that didn't work (I think all SVG files don't work):
[svgs.zip](https://github.com/luyadev/luya-module-admin/files/1567116/svgs.zip)
