### ISSUE TITLE
Admin UI: Page edit, main menu tree, make clear that items are draggable

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-module-admin#60]
<img width="225" alt="bildschirmfoto 2018-02-16 um 13 02 39" src="https://user-images.githubusercontent.com/15183757/36306864-df8ee3f6-1319-11e8-80b6-bfa90a51fce9.png">

It could be helpfull if on hover a small light, bit faded drag cross icon would show up on the right inside the menu item

**Comment by rolandschaub** [comment]
Or the cursor could change to the move pointer after 0.5 or so seconds.

**Comment by nadar** [comment]
Please do not use the closed issue.
