### ISSUE TITLE
Select Array validation rule don't work even if the attribute is defined as require

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya-module-admin#61]
When using the `selectArray` ngRest attribute type, the validation rule doesn't work even if the attribute is defined as required.

### Expected Result
On save or update, the form should show a message stating that the field cannot be empty

### What do you get instead?
The form being save or update without any validation

**Comment by nadar** [comment]
@JDL747 could you please provide the validation rules you where using?

**Comment by JDL747** [comment]
Rules
[['level'], 'integer'],

ngRestAttributeTypes
'level' => ['selectArray', 'data' => [1 => 'Amateur', 2 => 'Professionnel']],

**Comment by nadar** [comment]
@JDL747 have you tryed to change the handling of empty values?

https://www.yiiframework.com/doc/guide/2.0/en/input-validation#handling-empty-inputs

**Comment by nadar** [comment]
I just tested - yes i can confirm this won't work out of the box until you set the isEmpty validator as "0" is not an empty value.
