### ISSUE TITLE
Option to configure content-disposition with file downloads

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#64]
It should be possible to configure whether files are delivered with content-disposition set to "attachment" (as it is probably now) or "inline". That way it would be possible to define for each file link/button whether it should be downloaded directly or opened in the browser (if supported/allowed by browser). As an example, we have a client that would prefer press release PDFs linked from email newsletters to be opened in the browser.

**Comment by nadar** [comment]
@rolandschaub We could provide a global property for the admin module, this wold then appear to all files.

**Comment by rolandschaub** [comment]
No, I think this should be decided on a case by case basis when placing a download link. There are situations where a download and situations where an inline display is preferred.

**Comment by nadar** [comment]
@rolandschaub how would you do this? where do you store this information?

**Comment by rolandschaub** [comment]
I discussed it with @TheMaaarc: He found it's a good idea to set the default content-disposition in the app configuration but proposed to let this be overwritten by selecting a content-disposition option in the file manager on a file by file basis. Something like:

File delivery:
- default
- download
- show in browser

**Comment by nadar** [comment]
What we can configure in the response component:

```php
sendFile(['inline' => true/false]);
```

> inline: boolean, whether the browser should open the file within the browser window. Defaults to false, meaning a download dialog will pop up
