### ISSUE TITLE
TimestampBehavior behavior impact on textArray plugins

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya-module-admin#65]
### What steps will reproduce the problem?
When TimestampBehavior is defined in model containing textArray data attribute, saving the model in the admin with empty field generate a list of empty text array prevent of the updating the field

### What do you get instead? (A Screenshot can help us a lot!)
<img width="957" alt="screen shot 2018-02-24 at 18 24 29" src="https://user-images.githubusercontent.com/3844254/36633390-0da415e6-1995-11e8-87af-2467da5cdcd5.png">

**Comment by nadar** [comment]
Please provide full NgRest Model code.

**Comment by JDL747** [comment]
Another error with selectArray when using TimestampBehavior in model !

**Comment by nadar** [comment]
@JDL747 you need to provide more informations otherwise i can not help.

**Comment by JDL747** [comment]
[Model](https://gist.github.com/JDL747/895931792b7db34e3afc5ba4874c5854)

**Comment by nadar** [comment]
@JDL747 Then you have to provide the parent implementation as well when you override those.

```php
public function behaviors()
{
    $behaviors = parent::behaviors();
    // add yours
   return $behaviors;
}
```
