### ISSUE TITLE
Error in cleanup console command

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-module-admin#652]
### What steps will reproduce the problem?

Run `./vendor/bin/luya admin/storage/cleanup` as per https://luya.io/guide/luya-console
i.e. after an unused block file was deleted.

### What is the expected result?

Cleanup of db/storage

### What do you get instead? (A Screenshot can help us a lot!)

```
'Error' with message 'Class 'luya\admin\importers\StorageImporter' not found'

in .../vendor/luyadev/luya-module-admin/src/commands/StorageController.php:25
```

`StorageImporter` was removed a few years ago (https://github.com/luyadev/luya-module-admin/issues/268).

**Comment by nadar** [comment]
Yes indeed. I will remove anything related to storage cleanup system - or fix what should be kept.  There i even a new issue regarding this https://github.com/luyadev/luya-module-admin/issues/598

**Comment by nadar** [comment]
The problem with this command is that it won't work for different filesystems (for example https://github.com/luyadev/luya-aws s3 storage).

**Comment by hbugdoll** [comment]
Should we temporarily remove all `admin/storage/...` commands in the console command list of the guide (https://luya.io/guide/luya-console) ?

**Comment by nadar** [comment]
i removed the cleanup command https://github.com/luyadev/luya/commit/a1feb69b88337902466a4f97c30bc6a61a83a8f4
