### ISSUE TITLE
Misleading use of the note_add icon

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-module-admin#668]
**Introduction:** The `note_add` icon (page icon with a plus symbol) is used at several places in the LUYA ecosystem to represent an addition to something.
But it should only be used on the *Create new page* button in the CMS module, in the same way `create_new_folder`icon is used for the *Add folder* button.

<img width="242" alt="luya_add_buttons" src="https://user-images.githubusercontent.com/6715827/135634331-63fbd353-bb63-4f81-af0d-9c6a0282a96e.png">

(Therefor and for replacing the `note_add` admin menu icon another issue was opened in the CMS module repo: https://github.com/luyadev/luya-module-cms/issues/362)

---

The following changes are suggested:

**1.)** *User Preferences* > section *Devices*:
`note_add` --> `devices`

<img width="800" alt="luya_devices" src="https://user-images.githubusercontent.com/6715827/135637395-2bf8f785-1fea-4fd1-9c17-d3e5bde07b13.png">

**2.)** *System* > Addition log entry @ dashboard and other default dashboard (e.g. in the news module):
`note_add` --> `add_box`

<img width="800" alt="Dashboards" src="https://user-images.githubusercontent.com/6715827/135633458-2fee731d-b381-499f-ad3c-098af2b7ee26.png">

**3.)** AWS Overview (`ApiOverviewController`), AWS Group Auth (`ActiveWindowGroupAuth`), AWS User History (`UserHistorySummaryController`) and AWS User History Test (`UserHistorySummaryActiveWindowTest`):
`note_add` --> `add_box`

---

@nadar If you agree to this, I would make a PR.

**Comment by nadar** [comment]
sounds good to me :+1:
