### ISSUE TITLE
Sorting order in admin menu

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-module-admin#691]
A `modules` configuration
```
'modules' => [
        'admin' => [/*...*/],
        'cmsadmin' => [/*...*/],
        'myfirstmoduleadmin' => [/*...*/],
        'mysecondmoduleadmin' => [/*...*/],
        /*...*/
]
```
in the config file will result in the following admin menu order:

1. *Search*
2. *Dashboard*
3. MySecondModule menu items
4. MyFirstModule menu items
5. CMS module menu items (*Pages*, *CMS Settings*)
6. Admin module menu items (*Files*, *System*)

I found no option to sort the menu items by any sorting key.
The menu sorting order is obviously **reversed** to the order in `modules` array.
This behavior is unexpected and not documented.

---

An additional call of `ArrayHelper::multiSort($menu, ['id'], [SORT_ASC]);` in `AdminMenu::getMenu()` (line 114)
would respect the order in `modules` array:

1. *Search*
2. *Dashboard*
3. Admin module menu items (*Files*, *System*)
4. CMS module menu items (*Pages*, *CMS Settings*)
5. MyFirstModule menu items
5. MySecondModule menu items

To restore the familar LUYA menu manner (*Pages*, *CMS Settings* before *Files*, *System*) the CMS module would have to placed in front of the `modules` array:

```
'modules' => [
        'cmsadmin' => [/*...*/],
        'admin' => [/*...*/],
        'myfirstmoduleadmin' => [/*...*/],
        'mysecondmoduleadmin' => [/*...*/],
        /*...*/
]
```

1. *Search*
2. *Dashboard*
3. CMS module menu items (*Pages*, *CMS Settings*)
4. Admin module menu items (*Files*, *System*)
5. MyFirstModule menu items
5. MySecondModule menu items

---

Open Questions:
- That reordering breaks the BC regarding the UI. Is it still suitable?
- Is the order in the `modules` array relevant for module initialization?
- Should a sorting key (like in CMS menu) be introduced instead?

**Comment by nadar** [comment]
I think the idea of sorting them based on the config is a great idea. I did not make a research, but i think the menu items are stored in the database while importing. Sorting won't be possible after an import, it would only work "once while setup". I think the only solutions would be to have a new sort index for menu nodes and the option to change them in the admin ui. (which  requires a migration, and could be therefore an option for v5)

**Comment by hbugdoll** [comment]
@nadar Thanks for your reply.
I did some research.

1. In the database menu item-related `id`'s are only stored in table `admin_auth`.
In my opinion the `id`'s of the admin menu items are generated on the fly.

2. `ArrayHelper::multiSort($menu, ['id'], [SORT_ASC]);` is not a good idea,
but simply flip the parameters in

https://github.com/luyadev/luya-module-admin/blob/a198b86455c510c7ebc37ca843590a2ba52a54eb/src/components/AdminMenu.php#L112

to `$menu = ArrayHelper::merge($menu, $data);` will prevent the reversed order.

**Comment by hbugdoll** [comment]
> Open Questions:
> 
> * That reordering breaks the BC regarding the UI. Is it still suitable?

I will provide a PR with an advice in `UPGRADE.md`.

> * Is the order in the `modules` array relevant for module initialization?

Menu order is here not relevant.

> * Should a sorting key (like in CMS menu) be introduced instead?

No new sorting key is needed.
