### ISSUE TITLE
Alignment of language lists between backend and frontend

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#697]
Сurrently there is a difference between methods of getting language lists for backend and fronend, at least in the admin part.
In the first case languages are taken from 
https://github.com/luyadev/luya-module-admin/blob/4f6846fcd283f8ea21d1461f9bd954f39368fc58/src/components/AdminLanguage.php#L132-L155
while in the second case they are taken from 
https://github.com/luyadev/luya-module-admin/blob/4f6846fcd283f8ea21d1461f9bd954f39368fc58/src/apis/CommonController.php#L213-L221

I don't know if `is_deleted` should be taken into account in the second case, however the sort should be common in both cases. 

Now this difference leads to the fact that if we access the list of languages directly through the `AdminLangService`, the order of languages turns out to be different from the default in the admin panel (if the default language is not the first).

**Comment by nadar** [comment]
Thanks @Antikon, yes indeed the languages list should be the same as for AdminLanguage component, i will fix that. Thanks!

**Comment by nadar** [comment]
the `is_deleted` is taken into account, as it uses the https://luya.io/api/luya-admin-traits-SoftDeleteTrait
