### ISSUE TITLE
Login Screen: Password label doesn't move away when clicked

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#7]
On the login screen, when clicking on the email label, it moves away above the text field. When clicking on the password label, this doesn't work: the label only moves away when clicking to the right of it within the text field, see animation:

![login](https://user-images.githubusercontent.com/3786245/34119605-0bfda088-e423-11e7-9282-fe7883e83fb1.gif)

**Comment by nadar** [comment]
@dev7ch please add a changelog entry.

**Comment by dev7ch** [comment]
done.
