### ISSUE TITLE
Cant open panel admin 

### ISSUE THREAD

**Issue by kopolot** [luyadev/luya-module-admin#708]
I just installed luya as in the instruction and i cant open admin panel, when i try to login its gets me to the login site again and again 

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0
| PHP Version      | 7.4.28
| Platform         XAMPP
| Operating system | Windows 11

**Comment by nadar** [comment]
hi @kopolot thanks for your issue.

And this appears on your local machine? With Xampp? or docker? Is there a possibility that the ip changes or does the htaccess rule regarding auth headers not work? https://github.com/luyadev/luya-kickstarter/blob/master/public_html/.htaccess#L5-L6

**Comment by kopolot** [comment]
@nadar yes it appears on my personal laptop and work pc both on xampp. I think there isnt posibilty that htaccess rule dont work beacouse my custom url works well, but im not sure if it helps in anthing i use fresh reinstalled xampp with default settings.

**Comment by kopolot** [comment]
https://user-images.githubusercontent.com/18356802/161640004-69dd5272-9b8d-4147-847d-5958143e91c4.mp4

**Comment by nadar** [comment]
This looks like a very old version of luya. what does your composer json look like?

**Comment by kopolot** [comment]
composer 1.10.25, on 2.3.3 i cant index page

**Comment by kopolot** [comment]
basic file from luya page

**Comment by nadar** [comment]
Please install a fresh (and latest) kickstarter. Your Version is approx 4 years old, latest luya admin and cms Versions are 4.x

**Comment by kopolot** [comment]
thank you! Now i must update my work project but it works for me, you should update your page besacouse it can mislead

**Comment by nadar** [comment]
Which page?

**Comment by kopolot** [comment]
https://luya.io/

**Comment by nadar** [comment]
But there is nowhere an old version. or can you point me to that exact page where you found that?

**Comment by nadar** [comment]
glad it works now :+1:

**Comment by kopolot** [comment]
https://luya.io/guide/install-windows

**Comment by nadar** [comment]
but `composer create-project luyadev/luya-kickstarter:^1.0` will install the latest versions ....

**Comment by kopolot** [comment]
nope it instaled me version that didnt work

**Comment by kopolot** [comment]
i have to clone git repository from git composer.json vas for sure core 1.0 cms 1.0 admin 1.0
