### ISSUE TITLE
XSS SVG Security Issue

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#713]
https://huntr.dev/bounties/67492ce0-4d9e-4316-be37-fb6d029be030/

**Comment by sampritdas8** [comment]
@nadar It has been 2 months since I reported this vulnerability on huntr.dev so can you please validate it before the 25th of May so I can get the bounty from huntr.dev?

**Comment by nadar** [comment]
We checked that. This is not a critical issue for us. Admin users can turn this on or off, by default its on. We will switch to "default off", which might be better practicse. Thanks for the report.

**Comment by sampritdas8** [comment]
@nadar As you fixed the issue can you please valid it and confirm the fix from huntr.dev? As you said it is not critical according to you but according to other reports it is critical so can you please valid it and keep the severity as critical on huntr.dev?
