### ISSUE TITLE
Relation call problem

### ISSUE THREAD

**Issue by chemezov** [luyadev/luya-module-admin#736]
### What steps will reproduce the problem?

When open relation, throw 500 exeption.

Problem at this lines:
https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/render/RenderCrud.php#L188
https://github.com/luyadev/luya-module-admin/blob/master/src/ngrest/render/RenderCrud.php#L201

Property with type bool set with arrray.

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/2368902/196939474-43d64359-d078-4279-95b3-b8fcac3ff6a9.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 4.7.0 (latest)
| PHP Version      | 7.4
| Platform         | OpenServer
| Operating system | Windows

**Comment by nadar** [comment]
Indeed, will patch fix this asap! Thanks!

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/releases/tag/4.7.1
