### ISSUE TITLE
Relation gets lost when adding multiple relational records

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#742]
### What steps will reproduce the problem?

When adding a record that has a relation to another record (e.g. an article to a journal issue) the relation gets lost when saving the record with the «Create and new» button.

### What is the expected result?

The relation should not get lost so that multiple relational records can be added using the «Create and new» button.

### What do you get instead? (A Screenshot can help us a lot!)

The relation gets lost.

**Comment by nadar** [comment]
Can you provide a screenshot? or a relation config? I have tested in the news module and works as expected:

there are no news, only 1 category and i am going to add articles based on the category relation, the category relation is not lost afterwards:

![image](https://user-images.githubusercontent.com/3417221/209819186-9680d146-bcfb-4e9a-95c0-408ecd01fc85.png)

![image](https://user-images.githubusercontent.com/3417221/209819226-1eadf2f4-05d2-4e5f-99b8-f42633aef94d.png)

![image](https://user-images.githubusercontent.com/3417221/209819268-dd23f657-2938-42a3-aa0b-9d281cd95d3e.png)

![image](https://user-images.githubusercontent.com/3417221/209819319-d6fbc9f3-d9f8-4493-9c41-90e6e9cfc2a5.png)

relation works as expected:

![image](https://user-images.githubusercontent.com/3417221/209819386-a79cf1fe-0a0a-4fad-ad56-816a2b3323c4.png)

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-admin/pull/707
