### ISSUE TITLE
Admin page shows error while clicking on 'page permissions'

### ISSUE THREAD

**Issue by siripravi** [luyadev/luya-module-admin#747]
### What steps will reproduce the problem?

click Page Permissions I get the error

### What is the expected result?

I should be able to manipulate page settings

### What do you get instead? (A Screenshot can help us a lot!)
I get the following error while I click 'Page Permissions' in the admin page.
`yii\base\UnknownPropertyException: Setting unknown property: luya\admin\ngrest\plugins\Text::inline in C:\cakeshop\vendor\yiisoft\yii2\base\Component.php:210
Stack trace:
#0 C:\cakeshop\vendor\yiisoft\yii2\BaseYii.php(561): yii\base\Component->__set('inline', true)
#1 C:\cakeshop\vendor\yiisoft\yii2\base\BaseObject.php(108): yii\BaseYii::configure(Object(luya\admin\ngrest\plugins\Text), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 C:\cakeshop\vendor\yiisoft\yii2\di\Container.php(420): ReflectionClass->newInstanceArgs(Array)
#4 C:\cakeshop\vendor\yiisoft\yii2\di\Container.php(171): yii\di\Container->build('\\luya\\admin\\ngr...', Array, Array)
#5 C:\cakeshop\vendor\yiisoft\yii2\BaseYii.php(366): yii\di\Container->get('\\luya\\admin\\ngr...', Array, Array)
#6 C:\cakeshop\vendor\luyadev\luya-module-admin\src\ngrest\NgRest.php(73): yii\BaseYii::createObject(Array)
#7 C:\cakeshop\vendor\luyadev\luya-module-admin\src\ngrest\base\NgRestEventBehavior.php(81): luya\admin\ngrest\NgRest::createPluginObject('\\luya\\admin\\ngr...', 'name', 'Name', false, Array)
#8 C:\cakeshop\vendor\luyadev\luya-module-admin\src\ngrest\base\NgRestEventBehavior.php(45): luya\admin\ngrest\base\NgRestEventBehavior::findPluginInstance('name', Array, 'cms_nav_contain...')
#9 [internal function]: luya\admin\ngrest\base\NgRestEventBehavior->bindPluginEvents(Object(yii\base\Event))
#10 C:\cakeshop\vendor\yiisoft\yii2\base\Component.php(634): call_user_func(Array, Object(yii\base\Event))
#11 C:\cakeshop\vendor\yiisoft\yii2\db\BaseActiveRecord.php(943): yii\base\Component->trigger('init')
#12 C:\cakeshop\vendor\yiisoft\yii2\base\BaseObject.php(110): yii\db\BaseActiveRecord->init()
#13 C:\cakeshop\vendor\luyadev\luya-module-admin\src\ngrest\base\NgRestModel.php(89): yii\base\BaseObject->__construct(Array)
#14 C:\cakeshop\vendor\yiisoft\yii2\db\BaseActiveRecord.php(1219): luya\admin\ngrest\base\NgRestModel->__construct()
#15 C:\cakeshop\vendor\yiisoft\yii2\db\ActiveQueryTrait.php(122): yii\db\BaseActiveRecord::instantiate(Array)
#16 C:\cakeshop\vendor\yiisoft\yii2\db\ActiveQuery.php(220): yii\db\ActiveQuery->createModels(Array)
#17 C:\cakeshop\vendor\yiisoft\yii2\db\Query.php(252): yii\db\ActiveQuery->populate(Array)
#18 C:\cakeshop\vendor\yiisoft\yii2\db\ActiveQuery.php(134): yii\db\Query->all(NULL)
#19 C:\cakeshop\vendor\luyadev\luya-module-cms\src\admin\apis\MenuController.php(80): yii\db\ActiveQuery->all()
#20 [internal function]: luya\cms\admin\apis\MenuController->actionDataPermissionTree()
#21 C:\cakeshop\vendor\yiisoft\yii2\base\InlineAction.php(58): call_user_func_array(Array, Array)
#22 C:\cakeshop\vendor\yiisoft\yii2\base\Controller.php(179): yii\base\InlineAction->runWithParams(Array)
#23 C:\cakeshop\vendor\yiisoft\yii2\base\Module.php(553): yii\base\Controller->runAction('data-permission...', Array)
#24 C:\cakeshop\vendor\yiisoft\yii2\web\Application.php(104): yii\base\Module->runAction('admin/api-cms-m...', Array)
#25 C:\cakeshop\vendor\luyadev\luya-core\web\Application.php(52): yii\web\Application->handleRequest(Object(luya\web\Request))
#26 C:\cakeshop\vendor\yiisoft\yii2\base\Application.php(385): luya\web\Application->handleRequest(Object(luya\web\Request))
#27 C:\cakeshop\vendor\luyadev\luya-core\base\Boot.php(251): yii\base\Application->run()
#28 C:\cakeshop\vendor\luyadev\luya-core\base\Boot.php(195): luya\base\Boot->applicationWeb()
#29 C:\cakeshop\public_html\index.php(8): luya\base\Boot->run()
#30 {main}`

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
hi @siripravi 
what version are you using? can you show the composer.json? do other crud's work? 

The inline property exists, but maybe you have an old version?

**Comment by nadar** [comment]
(as you can see here https://api.luya.io/luya-admin-ngrest-plugins-text#$inline-detail)

**Comment by siripravi** [comment]
I also got the error when I delete a page(Home page) and created a new one and trying to save it as a "default page".
