### ISSUE TITLE
migrate using windows systems

### ISSUE THREAD

**Issue by jilmacs** [luyadev/luya-module-admin#75]
i have tried to use migrate using php index.php ./vendor/bin/luya migrate but nothing happens.

**Comment by jilmacs** [comment]
![image](https://user-images.githubusercontent.com/37847476/37991415-f0c7e286-31bd-11e8-8c7a-fbe8223af5ca.png)

**Comment by nadar** [comment]
Please try windows install instructions https://luya.io/guide/install-windows

**Comment by nadar** [comment]
you should use `php index.php migrate` instead of `php index.php ./vendor/bin/luya migrate`
