### ISSUE TITLE
The content inside placeholders are not shown in the frontend. 

### ISSUE THREAD

**Issue by siripravi** [luyadev/luya-module-admin#750]
### What steps will reproduce the problem?

I am using **luya-kickstarter-bootstrap4** with the following modules:
 ```
  "luyadev/luya-module-admin" : "^5.0",
   "luyadev/luya-module-cms" : "^5.0",
```

I have this in for cms layout.

```
<div class="row">
    <div class="col-12">
        <?= $placeholders['top']; ?>
    </div>
    <div class="row">
        <div class="col-md-8" style="border:5px solid red;">
            <?= $placeholders['left']; ?>
        </div>
        <div class="col-md-4">
            <?= $placeholders['right']; ?>
        </div>
    </div>
    <div class="col-12">
        <?= $placeholders['bottom']; ?>
    </div>
</div>
```

### What is the expected result?

The content for all the 4 placeholders should be loaded and shown in the frontend.
Earlier, I used 'left' and 'right' only. I guess, after updating the layout, 

### What do you get instead? (A Screenshot can help us a lot!)

It shows the content placed in 'left' and 'right' placeholders only. Not for 'top' & 'bottom'.

But in admin preview, It shows all the four placeholders intact.

<img width="394" alt="pinfo" src="https://github.com/luyadev/luya-module-admin/assets/174201/ea0d871f-212d-45a0-a752-af987fa1104c">

### LUYA Check ouput (run this script and post the result: [luyacheck.php]
(https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by siripravi** [comment]
<div class="row">
    <div class="col-12">
        <?= $placeholders['top']; ?>
    </div>
    <div class="row">
        <div class="col-md-8" style="border:5px solid red;">
            <?= $placeholders['left']; ?>
        </div>
        <div class="col-md-4">
            <?= $placeholders['right']; ?>
        </div>
    </div>
    <div class="col-12">
        <?= $placeholders['bottom']; ?>
    </div>
</div>

**Comment by nadar** [comment]
But in the screenshot, i can see that there are not content blocks placed in the top and right placeholders?

**Comment by siripravi** [comment]
I added the content. Still only left & right are shown.
<img width="228" alt="added" src="https://github.com/luyadev/luya-module-admin/assets/174201/ada38f4b-5971-4383-a492-412fbc6193ea">

**Comment by siripravi** [comment]
Other layouts are working just fine.
<?php
/**
 * @var string[] $placeholders
 */
?>
<section id="header" class="wrapper">
    
    <div class="header-container">
        <?= $placeholders['intro'] ?>
    </div>
</section>


<section id="main" class="wrapper">
    <?= $placeholders['main'] ?>
</section>

<?php if ($placeholders['highlights']) : ?>
    
    <section id="highlights" class="wrapper style3">
        <div class="container">
            <?= $placeholders['highlights'] ?>
        </div>
    </section>
<?php endif ?>

**Comment by nadar** [comment]
1. try to run the import command https://luya.io/guide/cms/blocks.html#register-and-import
2. check if there is a json file next to the cms layout, and if this contains the same placeholder names, https://luya.io/guide/cms/cmslayouts.html#create-new-layout
3. Ensure to disable caching on localsystem, maybe the data is cached.
4. make a `var_dump($placeholders)` and post the output here, please format your issues and comments accordingly! => https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

we use that system (with latest version) in so many sites and don't have a problem, soudns curious to me.

**Comment by siripravi** [comment]
The issue is with another layout file with the same placeholder names. I resolved the issue by using different names throughout. Possibly the issue.
Thank you.
