### ISSUE TITLE
No icons in all dashboard

### ISSUE THREAD

**Issue by neoacevedo** [luyadev/luya-module-admin#761]
### What steps will reproduce the problem?

Following steps to install luya.

### What is the expected result?

The dashboard with all material icon.

### What do you get instead? (A Screenshot can help us a lot!)

<img src="https://github.com/luyadev/luya-module-admin/assets/438372/07e2131a-156d-49a9-ad40-8952fafd1e00" width="640">

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

```
PHP Fatal error:  Uncaught Error: Call to undefined function apache_get_modules() in /app/luyacheck.php(23) : eval()'d code:1
Stack trace:
#0 /app/luyacheck.php(23): eval()
#1 {main}
  thrown in /app/luyacheck.php(23) : eval()'d code on line 1
```

The script can't be executed.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version  | 2.3 (?)
| PHP Version      | 8.2
| Platform         | Apache or nginx
| Operating system | Linux (docker)

**Comment by nadar** [comment]
what does your composer.json look like? what versions?

**Comment by neoacevedo** [comment]
```
{
    "name": "luyadev/luya-kickstarter-bootstrap4",
    "description": "LUYA boilerplate to kickstart projects with Bootstrap 4.",
    "type": "luya-kickstarter",
    "license":"MIT",
    "require": {
        "luyadev/luya-module-admin" : "^4.0",
        "luyadev/luya-module-cms" : "^4.0",
        "luyadev/luya-bootstrap4": "^1.0",
        "luyadev/luya-generic" : "^1.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug" : "^2.0",
        "yiisoft/yii2-gii" : "^2.0",
        "luyadev/luya-deployer": "^1.0",
        "twbs/bootstrap": "^4.0"
    },
    "config": {
        "fxp-asset": {
            "enabled": false
        },
        "allow-plugins": {
            "yiisoft/yii2-composer": true,
            "luyadev/luya-composer": true
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```

**Comment by nadar** [comment]
cms should be ^5.0 not 4.0. also for the admin it should be ^5.0` not 4.0

**Comment by neoacevedo** [comment]
As in your post, https://github.com/luyadev/luya-kickstarter-bootstrap4/issues/35#issuecomment-2081985337, a part is about the composer.json lines 7 & 8, now, what I see in the browser dev tools is the font is never loaded:

<img src="https://github.com/luyadev/luya-module-admin/assets/438372/42cfebf6-fcee-4844-8a0c-b73326fb7377" alt="" width="640">

It means, resources/scss/admin.scss is not compiled, so the font and the material style won't be loaded. The project only has resources/dist/main.css and resources/dist/login.css

**Comment by nadar** [comment]
hi @neoacevedo but what version does that project in your screenshot now have? latest cms and admin versions? 

please show all requests from the network tab, so we can see the path of the fonts trying to be loaded.

we never ha problems with fonts actually, should work as expected, it sounds strange.

**Comment by neoacevedo** [comment]
Latest cms and admin versions. I run the composer update after setting the version to ^5.0 in the lines 7 and 8 in the luya's composer file.

![imagen](https://github.com/luyadev/luya-module-admin/assets/438372/19875380-cc47-4032-ae91-9c320a53c2b6)

I'm tryng to guess the reason but my guess is what I said above.

**Comment by nadar** [comment]
all files all available in the resources folder of your vendor, `vendor/luyadev/luya-module-admin/src/resources ... ` there you will find the fonts and in the dist the main.css which is loaded.

the screenshot does not help, because you should show the fonts "loading", check this:

![image](https://github.com/luyadev/luya-module-admin/assets/3417221/82186054-f348-48eb-8c73-e49f280a3e2f)

**Comment by neoacevedo** [comment]
The typography isn't loaded:

![imagen](https://github.com/luyadev/luya-module-admin/assets/438372/e0dbc737-a480-4af3-a7bc-39eceb1a2203)

There are also 2 main.css files:

```html
<link href="/assets/6d581216/dist/main.css" rel="stylesheet">
<link href="/assets/cf62873b/dist/main.css" rel="stylesheet">
```

The first one is for this module, but the second one is for the cms module. I think that's causing me the issue about the material icon fonts.
