### ISSUE TITLE
Disable click on column of type toggleStatus

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya-module-admin#77]
When a user have read access only for a module, in the list view, the user should not be able to click on column of type `toggleStatus`.

### Current behaviour
Actually, the user with restricted access can still click on the item but get logged out instantly. An exception of permission denied is then occurs.

**Comment by nadar** [comment]
@JDL747 should be fixed, cloud you please try install latest dev-master and give feedback. Thanks for the report.

**Comment by JDL747** [comment]
@nadar Tested and works as expected !
