### ISSUE TITLE
Update russian translation to keep lables in bounds

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#79]
Hi!

Some admin sidebar labels are out of bounds.

Before:

![before](https://user-images.githubusercontent.com/1450983/38176965-4ef5149a-3601-11e8-8baa-5bd02e950a2f.png)

After:
![2018-04-01 23 03 49](https://user-images.githubusercontent.com/1450983/38176968-58be0cfc-3601-11e8-93c4-b353f33c1ede.png)

All translations are correct and the same sense.

PR: https://github.com/luyadev/luya-module-admin/pull/78

**Comment by nadar** [comment]
Thank you very much @nick-denry !
