### ISSUE TITLE
Adjust confirm and abort buttons naming

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#82]
Hi! 

Usually there are two well-known practice of a confirm/abort buttons naming.

1.Yes/No 
or
2. Ok/Cancel

Now it used mixed Cancel / Yes for, i.e. for file delete confirmation. I guess it is better to use one of two common practice for all translations.

https://github.com/luyadev/luya-module-admin/blob/72b7b0791939ebab3c693f8e08773f29cfc63ace/src/messages/en/admin.php#L6
https://github.com/luyadev/luya-module-admin/blob/72b7b0791939ebab3c693f8e08773f29cfc63ace/src/messages/en/admin.php#L7

The result is

![Confirm buttons](https://user-images.githubusercontent.com/1450983/38250208-d5718214-3756-11e8-94b2-dd6874169315.png)

What do you think?

**Comment by nick-denry** [comment]
The result could be 

![YesNo](https://user-images.githubusercontent.com/1450983/38251202-76e5757c-3759-11e8-8ff5-b8fe67b0b86d.png)

![OkCancel](https://user-images.githubusercontent.com/1450983/38251208-7cc38682-3759-11e8-8b44-acedcaaf186e.png)

Or even use more context, but it needs additional label

![CancelDelete](https://user-images.githubusercontent.com/1450983/38251233-8fa0a87a-3759-11e8-8d3a-4e15de1564fb.png)

Cancel/Delete for deletion and Cancel/OK for settings etc.

**Comment by nick-denry** [comment]
> [Cancel] [Yes]

It's a bit violating some guides like e.g. msdn practice

> Don't use Cancel buttons to respond to questions.
> Incorrect:

![Incorrect](https://msdn.microsoft.com/dynimg/IC726302.png)

Pls check this https://msdn.microsoft.com/en-us/library/windows/desktop/dn742499(v=vs.85).aspx
and maybe this this https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150

IMHO following on of the popular guides (any) will be better for Luya using/promotion. But I am not insisting on that, of course.

**Comment by nadar** [comment]
> Don't use Cancel buttons to respond to questions.

So we maybe should use NO / YES instead of CANCEL / YES? @luyadev/coredev ?

**Comment by rolandschaub** [comment]
Apple, as an example, uses the following for a delete dialogue:

Are you sure you want to delete the file "Manuscript.doc"?

[Cancel]  [Delete]

So the buttons are labeled with two actions, which I prefer to "Yes" and "No".

**Comment by nadar** [comment]
Delete is a contextual information we don't have currently.

**Comment by rolandschaub** [comment]
Is it difficult to add this feature?

Otherwise I could live with both [Cancel] [OK] or [Cancel] [Yes].

**Comment by nadar** [comment]
@rolandschaub its not about difficulty, its about finding all dialogs and add translation messages.

**Comment by nadar** [comment]
I prefer **Cancel | Yes** over **Cancel | OK** - so cancel yes is what we have right now...

**Comment by nick-denry** [comment]
@nadar Then you could close this issue I think.

**Comment by nadar** [comment]
@nick-denry all right, but thanks for thinking about those things, please create a new issue if you think we could improve the UI.
