### ISSUE TITLE
Remove spellchecking for file upload button

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#91]
Storage upload button has unwanted spell checking in Firefox 59.0.2 if btn text clicked.

![2018-04-10 01 12 55](https://user-images.githubusercontent.com/1450983/38525807-5b26fe48-3c5c-11e8-988c-e7e64039e327.png)

This happens because button has `contenteditable` attribute set to `true`. For me it woks with `contenteditable` attribute set to `false` via browser debug panel, but if it is really needed, html5 attribute `spellcheck="false"` should be set.

https://html.spec.whatwg.org/multipage/interaction.html#spelling-and-grammar-checking

**Comment by nadar** [comment]
@nick-denry @TheMaaarc I have never seen such a correction. But if spellcheck="false" works, we should do this maybe.

**Comment by nick-denry** [comment]
I guess that problem will occur only at Linux i18n version of FF, cause spellchecking language there is set to English by default no matter what the real FF UI language is. So, it's maybe a small percentage of users affected, but there is no need for spellchecking anyway.

**Comment by nadar** [comment]
would you like to send a PR @nick-denry?

btw: https://caniuse.com/#feat=spellcheck-attribute

**Comment by nick-denry** [comment]
@nadar I'm a bit late, sorry. Stackoverflow says that spellcheking on mobile browsers can be disabled too.

Have a look on this https://stackoverflow.com/a/254716 pls. Should we do that?

**Comment by nadar** [comment]
mobile browser should respect spellcheck=false.

**Comment by nick-denry** [comment]
> mobile browser should respect spellcheck=false.

No. Information from your link https://caniuse.com/#feat=spellcheck-attribute

> The partial support in mobile browsers results from their OS generally having built-in spell checking instead of using the wavy underline to indicate misspelled words. spellcheck="false" does not seem to have any effect in these browsers.

**Comment by nick-denry** [comment]
Why do we need `contenteditable="true"`?

**Comment by nadar** [comment]
contenteditable is because of the drag and drop possibiltie i assume.

Sure we can also provie `autocomplete="off" autocorrect="off" autocapitalize="off"` if you like. Please send a PR.
