### ISSUE TITLE
NgRest CRUD form required fields should have highlighting

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#94]
Hi!

If form has a lot of fields it is hard to realize what fields should be filled in spite of pop-up roasters.

Neither star sign (*) or highlight nor html5 attribute `required` presented on required fields.

E.g. this form is long enough so it is required to search field-by-filed with your eyes to compare field labels with pop-up text instead of just fill "red-highlited-fields".

![2018-04-12 01 27 31](https://user-images.githubusercontent.com/1450983/38646553-224a4e7c-3df1-11e8-92e3-623c3750f91f.png)

![2018-04-12 01 33 57](https://user-images.githubusercontent.com/1450983/38646681-9a086dea-3df1-11e8-94e4-e2873b849cce.png)

**Comment by nick-denry** [comment]
Yes, right. For me it is not useful if it needs to fill form fast. 

 You could try yourself if you'll create a long form with random distribution of the required fields.

**Comment by nick-denry** [comment]
I've placed required fields of the form upwards into first accordion, it's a bit helps, but better use some indication I think.

**Comment by nadar** [comment]
Yes i agree.
