### ISSUE TITLE
Customising the tab Label Attribute

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya-module-admin#96]
To be able to customize the `tabLabelAttribute` for `ngRestRelations`

Ex.
`tabLabelAttribute => function($model) { return 'whatever field I want'; }`

or another way is to :

pass an extra field to `tabLabelAttribute` without defining it in the `ngRestScopes` list array

**Comment by nadar** [comment]
This option exists already:

> If you like to display the name of the current element in the tabe you can define 'tabLabelAttribute' => 'fieldName' where fieldName is the name of the attribute in the list overview.
